### ISSUE TITLE
Key bindings do not allow single keys / simple keys (without Ctrl or Alt modifier)

### ISSUE THREAD

**Issue by wedeluxe** [Komodo/KomodoEdit#1102]
### Short Summary

+ Open `Preferences > Key Bindings`
+ Select a command
+ Set Focus to the "New Key Sequence" box

I tried to remap several of the simple keys on my keyboard (like ^ / SHIFT+^ / < / SHIFT+< / ä / ö / ü).
Komodo Edit refuses these keys, telling me _This key combination is not available._

Remapping of all key sequences should be allowed.

### Platform Information

+ GNOME 3.16.2 on Arch Linux 64-bit
+ Komodo Edit, version 9.3.2, build 16460, platform linux-x86_64

**Comment by cgchoffman** [comment]
Is there a particular reason you're asking for this?  This reminds me of Emacs or Vi mode.  Those aren't what you're looking for by any chance are they?

**Comment by wedeluxe** [comment]
No, they aren't.

The reason is usability.

+ The keys I mentioned are never used when writing software, commenting code and similar.
+ So I would love to remap the umlaut-keys to insert braces and brackets (those are a pain to enter on a German keyboard layout).
+ The ^ key is positioned right below the ESC key, it is by far my favourite key to remap in each and every application. It is great to toggle panes, cycle the focus.

And there's way more use cases and other simple keys to remap ...

**Comment by cgchoffman** [comment]
Is this even possible @mitchell-as?  Can we have commands mapped to single keys without using modifier keys to notify scintilla that a keybindings is incoming?

**Comment by mitchell-as** [comment]
I would imagine that Mozilla allows for this. Ultimately it should forward meaningful key combinations to Scintilla for input. @Naatan would know more about this than me.

**Comment by Naatan** [comment]
To be honest I think this is out of scope. What you are talking about is remapping keys, which is not what we offer. We offer you to set keybindings - ie. key combinations.

We could support key mappings, but I'm personally not to keen on doing this as I fear the cons outweigh the pros.

Those being:

Pros:
 - You get to use keys that otherwise go to waste 

Cons:
 - Very few people would actually have a use for this
 - This sounds like something that could cause a ton of confusion (why did my S key stop working?!)
 - It could pose significant challenges for custom key event handling code that was not designed with this in mind

Those things considered I think it would make more sense for people who really want this to just write a simple userscript for this. Eg:

```
if (typeof(extensions) === 'undefined')
    extensions = {};
if (extensions.CustomMappings && extensions.CustomMappings.onKeyPress) {
    document.removeEventListener('keypress', extensions.CustomMappings.onKeyPress, true);
}
extensions.CustomMappings = {};

(function()
{
    var editor = require("ko/editor");
    this.onKeyPress = function(e)
    {
        if (e.which == 123) // opening bracket
        {
            editor.insert("foobar");
            e.preventDefault();
        }
    };
    
    document.addEventListener('keypress', this.onKeyPress, true);

}).apply(extensions.CustomMappings);
```

Mind you most of that is boilerplate.
