### ISSUE TITLE
Editor: Can't highlight multiple lines of text then tab

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1117]
### Steps to Reproduce

1. Select mutliple lines of code
2. hit tab

### Expected results

the selected block to be tabbed

### Actual results

The entire block is selected, including white space that may not be selected at start and end of block, but it's not tabbed

### Errors / Logs

Unfortunately I don't notice an errors appearing :(

**Comment by mitchell-as** [comment]
That's odd. I cannot reproduce this with plain text or Python. What language are you using? Is there something weird going on with your profile?

**Comment by Naatan** [comment]
Is this on 9.3.2?

**Comment by cgchoffman** [comment]
@Naatan This is the nightly.  I noticed it in Javascript files @mitchell-as.  I suspect this is related to the indent bug I reported #1106 but there is no error :(.  The action fits though.  It highlights the block first, then attempts to tab but just stops.

**Comment by mitchell-as** [comment]
I downloaded the nightly from yesterday and still cannot reproduce this.

**Comment by cgchoffman** [comment]
@mitchell-as, I think you need my prefs.XML file. https://github.com/Komodo/KomodoEdit/issues/1106#issuecomment-188867079

If you can't repro with that then lets ignore this.  I've since reset my prefs file to a previous version and things are back to normal though it would be good to know why my prefs are breaking stuff.

**Comment by mitchell-as** [comment]
I think you have a userscript or something bound to the 'Tab' key, because I have the following Python code:

    foo
    bar
    baz

1. I select the first two lines and press Tab, but nothing happens.
2. However, when I go past the first 'b' in the second line (b|ar) and press Tab, "baz" autocompletes and I get "bazar".
3. When I go to the beginning of the first line and press Tab, "foo" indents as expected. 
4. Then when I select the first two lines and press Tab again, both lines indent as expected. Perhaps the userscript doesn't get triggered anymore for whatever reason.

**Comment by tonyattwood** [comment]
Hi,

I'm writing a review on  an interesting book  right  now,  please read some extracts here <http://explore.makeovermama.com/e4mjsxb> and tell me what you think.


Regards, tony.attwood@ntlworld.com
