### ISSUE TITLE
New UI: Opening Color Scheme Asks for Saving Preferences Superfluously

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1149]
1. Start with a clean Komodo profile.
2. Edit > Preferences > Color Schemes.
3. Komodo asks me to save my preferences, but I haven't changed anything.

I'd expect the prefs window to just close automatically if my prefs aren't in a "dirty" state.

**Comment by Naatan** [comment]
Unfortunately because of how the pref windows are written this is not possible without false positives. ie. in most cases I could indeed detect whether the prefs are dirty but in some cases the pref changes are deferred to the user pressing OK or Apply. The current solution simply checks if any other pref panes have been opened.

I'm not against the possibility of false positives, but unconvinced. Thoughts?

**Comment by Naatan** [comment]
Closing as there is no better solution available.
