### ISSUE TITLE
Show bookmarks in minimap

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1156]
### Short Summary

Show bookmarks in minimap. not much else to say I don't think.

**Comment by mitchell-as** [comment]
I thought this would be a piece of cake, but it's not, due to our minimap implementation. I thought it was as easy as making the markers visible by changing their line's background. This works when a marker is outside the current view, but as soon as I scroll the bookmark into view, it "disappears" from the minimap. Then when I scroll past it it "reappears". (See the three screenshots below that demonstrates this. My bookmark is on line 249.)

![1](https://cloud.githubusercontent.com/assets/12902397/16130252/478e92a0-33d6-11e6-970a-711b397eae8b.png)
![2](https://cloud.githubusercontent.com/assets/12902397/16130255/498cb582-33d6-11e6-8a6d-cd1736b45ea4.png)
![3](https://cloud.githubusercontent.com/assets/12902397/16130256/4b7b09ca-33d6-11e6-9058-108fd6804a5c.png)

This happens because the "thing" in the minimap that shows the current region in the document that is currently visible is just a big selection (that's right, a bunch of lines are selected, which gives the appearance of a scrollbar "thing"). I tried to make the selection a bit transparent to let the bookmarked line show through, but I lost the selection effect and now it's not easy to see what part of the document you are looking at. (See below.)

![4](https://cloud.githubusercontent.com/assets/12902397/16130332/a0add8aa-33d6-11e6-8210-92f14ab73628.png)

Short of creating a translucent overlay box that outlines the current part of the document in view (thus removing the need to make a big selection), I'm not sure how feasible this is. I'd recommend closing this ticket.

**Comment by Naatan** [comment]
I will experiment with the feasibility of using some type of UI element for the scrollbar handle. It's worth looking into because it seems if we want to do anything with the minimap going forward we will need to address this.

**Comment by Naatan** [comment]
Closing in favour of #1887
