### ISSUE TITLE
Go to definition from HTML to CSS

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#124]
Just a feature request. 
http://forum.komodoide.com/t/go-to-definition-not-working/798
https://bugs.activestate.com/show_bug.cgi?id=90981

**Comment by Defman21** [comment]
With CSS auto-completions in HTML you implemented in Komodo 9.3, I think that this feature should be implemented too. It's very useful in my opinion.

**Comment by Naatan** [comment]
@mitchell-as thoughts?

**Comment by mitchell-as** [comment]
This is not trivial. You'd have to walk up the tag chain to see what the full selector is and try to find the equivalent CSS selector (which may not match exactly due to the nature of CSS). If you don't walk the chain but focus only on the id/class name, you can have multiple class/id styles in multiple places, and goto definition would only go to one of them. (Therefore I don't think that version is useful.)

**Comment by Defman21** [comment]
Okay, I have another idea. When you click on an id/class, a popup appears with the items which refers to CSS files where the id/class is defined.

**Comment by Naatan** [comment]
I think at that point it becomes a pretty niche feature. Gonna close this as it does not some feasible, maybe it makes sense to do something with this in the future but it needs more thought and it needs to be something that is actual useful to the general user.
