### ISSUE TITLE
Debugger: Start/Find/Hide Default Interactive Shell command (F12) is confusing

### ISSUE THREAD

**Issue by Mook-as** [Komodo/KomodoEdit#1264]
### Short Summary

The command that toggles the default shell has confusing behaviour with focus.

### Steps to Reproduce

1. Open a new window.
2. Press `F12`
3. Go to 2.

### Expected results

1. The (Python) shell opens when you first press `F12`. Keyboard focus is in the shell.
2. The shell hides when you press it again.
3. Hereafter, focus the shell on `F12` if it wasn't previously focused, otherwise close it.

### Actual results

1. On first press, the shell opens, but focus doesn't go there.
2. On second press, the focus moves there. (Good!)
3. On third press, the shell closes (Good… enough?), the console shows up instead (shouldn't the whole bottom pane close?), and focus is moved to the editor (Good)
4. On fourth (and subsequent) presses, nothing happens. (Not good).

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88858, platform linux-x86_64.
Built on Fri Apr 15 02:30:01 2016.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/f0181613a939565c22c82128252fba32184e7725

Note: this has not been working since Komodo 8. In Komodo 7, the bottom pane toggled between visible/invisible, but the tab itself did not. I chose to toggle the focus between the editor view and the interactive shell on each F12 keypress, rather than toggling the visibility of the bottom pane (which may have been open to start with, so the toggling would be undesirable). You can probably bind a key to toggle the visibility of the bottom pane in addition to toggling focus between editor and interactive shell.
