### ISSUE TITLE
Unable to scroll to end of long lines, text wrap has no effect. 

### ISSUE THREAD

**Issue by jpshdev** [Komodo/KomodoEdit#1273]
### Short Summary
When viewing a file with very long lines of text, using the scroll bar to move to the right does not show the remaining text. The only way to reveal the text is to position the insertion point on the end of the visible line and use the right arrow key. Turning on line wrapping has no effect on these lines as well. 

### Steps to Reproduce

I see this most often in html or twig files with long lines (in some cases over 400 columns), but this may be because these files tend to have long lines, where other file types (.conf, .php, etc.) do not. 

### Expected results

Scrollbars and scroll wheel should allow for scrolling to the end of the line. 

### Actual results

Scroll stops before the end of the line

### Platform Information

*Komodo IDE* 
*Komodo Version?* 9.3.2, build 88191
*Operating System (and version)?* Mac OS X 10.11.4

**Comment by jpshdev** [comment]
This appears to be a duplicate of https://github.com/Komodo/KomodoEdit/issues/976

Closing

**Comment by cgchoffman** [comment]
If you look at the entire ticket, the issue is different from what I assume you're reporting.  You can get to the end of your lines by using cmd + right arrow.  This is a limitation in the underlying editor we use.  It is unaware of it's entire potential width so it can't report it to our wrapper.

There is no plan to patch this and the upstream isn't accepting patches for it as far as I know.

**Comment by cgchoffman** [comment]
Here is a bit more information to clarify.  From the upstream opensource project: http://scintilla.org/ScintillaDoc.html#SCI_SETSCROLLWIDTH
