### ISSUE TITLE
Scrollbar shows when minimap is enabled

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1304]
Title

**Comment by mitchell-as** [comment]
Additional info: `views-editor.p.xml`'s `updateMinimapDisplay` appears to set the Scintilla `vScrollBar` setting for showing the vertical scroll bar properly, but for some reason that setting is not being honored. I even tried to use the console to manually turn off the scrollbar (both vertical and horizontal) but there was no effect. I find it hard to believe that Scintilla is the culprit here in light of this.

**Comment by cgchoffman** [comment]
Thanks @mitchell-as, when i tried manually disabling the scrollbar in scintilla like you said i also tried enabling it.  Turns out the scrollbar was for the minimap view, not the editor.

**Comment by Naatan** [comment]
@cgchoffman your fix only disables the scrollbar. Wouldn't this mean that disabling the minimap would leave you with no scrollbar?

**Comment by cgchoffman** [comment]
@Naatan no, my change is in `views-minimap.xml`, not `views-editor.xml`.  I double checked though and the scrollbar is brought back in your editor when you disable mini-map again.
