### ISSUE TITLE
Auto detect indentation doesn't work

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1310]
### Short Summary

Indentation seems to always use your preferred spacing/tabbing regardless of the option to allow file contents to override this setting being set or not.

### Steps to Reproduce

Open a file with an indentation of 2 spaces (eg. prefs.p.xml, bindings.less, windows.p.xml)

### Expected results

Indentation is detected as 2 spaces

### Actual results

Indentation is 4 spaces

**Comment by mitchell-as** [comment]
This happens on a clean profile because the first start wizard explicitly sets "indentWidth" to 4 (if you're using spaces, not tabs). This seems to override the default "useSmartTabs" setting, so all indentation is assumed to be set at 4 spaces. Having the wizard explicitly set "useSmartTabs" to 1 should fix this.

(I did find a logic bug related to a small subset of XML-type documents that prefs.p.xml and windows.p.xml fall under.)
