### ISSUE TITLE
Feedback on "Let's Get Started" window: Classic mode is not clear. what it means

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1338]
![ki10-20160430](https://cloud.githubusercontent.com/assets/2390335/14938418/dbf947bc-0edf-11e6-8a44-6962f38daffe.png)

Extra set of window controls (although not native ones?) in the upper right corner of the first "Let's Get Started" window.

In addition, it seems like some indication of what "Classic mode" is/does would be really helpful for both new and migrating users.

**Comment by cgchoffman** [comment]
buttons is: #1307
Missing preview is #1306
Classic mode is what the sentence after implies but it could possibly be more clear.  it doesn't use the new UI (or fakes the old one.  @Naatan can better answer that.

This feedback is awesome Ron but please make sure bugs haven't been filed for stuff.  I see the other ones coming, they look good.  Thanks a lot.

Also, please don't file 3 bugs in one report.  it's a very good way to have things not get fixed (eg. fix two items and miss the 3rd by accident).

I'm going to change the description to reflect the item that is left in this report.

**Comment by we3geeks** [comment]
@cgchoffman Thanks for the follow-up and the feedback (on my feedback) :) Clearly my github-fu is not up to snuff in many ways. Is there an easy way to look at all issues logged against v10, regardless of their status? 

I looked but missed the entry for #1307 somehow. I was trying to provide feedback on each of the windows as a whole, but will be more granular going forward.

**Comment by cgchoffman** [comment]
I think you're best bet is to start with [Milestone 10](https://github.com/Komodo/KomodoEdit/milestones/10.0) then drill down from there.  We've also been using the "new" label to explicitly mean "this was introduce because of a new feature, workflow in komodo 10, eg. the Getting Started Dialog.
Also make sure to remove `is:open` that github automatically adds to the search box.  You wouldn't have seen #1307 or #1306 because they are fixed and closed.
So as a recap, to find both of those issue i used the following search params `milestone:10.0 osx ` and those two issues were near the top.  helps to have key worded descriptions when filing bugs, think of what people will look for  (or you would look for) when they are checking for an existing issue.

I now seee what you were going for with each dialog screen.  More than one issue reported actually does makes sense in that context.

Ok i think i've talked your ear off enough.

Thanks again for joining in on the testing party!

**Comment by mitchell-as** [comment]
A description on classic mode is all that is needed in this ticket.

**Comment by Naatan** [comment]
I'll add this:

![image](https://cloud.githubusercontent.com/assets/278649/14959531/cb5e1b56-105d-11e6-99b1-dbfd07959a13.png)
