### ISSUE TITLE
Feedback on 2nd "Let's Get Started" window

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1339]
![ki10-20160430c](https://cloud.githubusercontent.com/assets/2390335/14938429/45cceff4-0ee0-11e6-8c08-69ba4cc0d12b.png)

Color selections make it basically impossible to read what the indent value is.

"Behaviour" has that weird British spelling, which I would be OK with if the first "Let's Get Started" screen used "Colour" (it doesn't). Should probably be "Behavior" for consistency?

The vertical positioning of the "Snippet Behaviour" label -- centered in comparison with the two radio buttons looks odd. Seems like it should be aligned with the top radio button. And a bit of whitespace to vertically separate those two radio buttons form the checkboxes below them would help mentally break those groups of choices apart.

**Comment by Naatan** [comment]
Thanks @we3geeks! The color selection issue you already filed in a separate bug so I won't handle that here. I'll change Behaviour > Behavior. As for the spacing; this appears to be working correctly, the label is always vertically centered, but because the first label is only for one row and the second is for 2 rows (the 2 radio boxes) you can't quite tell.
