### ISSUE TITLE
Python Debug: separate console: raw_input() won't take input

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1450]
### Short Summary

Testing #1442 I found that I can't input anything when the new console window opens.  

### Steps to Reproduce

Create Python file with the following content:

```python
print bool(raw_input())
```

Start debugger (doesn't matter if its `run without` or just a regular debug session) and select separate console.
Click `Ok`

### Expected results

To be able to add input into console that is opened

### Actual results

Can add any input to new console.

### Additional Information

If you click the "play" button in the debugger pane in the Komodo window you'll get a prompt that you can interact with properly.  It will take input then print the result as expected.  The external terminal will remain open even when the debug session ends.

**Comment by mitchell-as** [comment]
This is not a regression and present in Komodo 9. I'm not sure it has ever worked...

**Comment by mitchell-as** [comment]
After looking into this, I found that our dbgp client redirects stdin from the child process to a pipe that Komodo's debug output window sends input to. Therefore it doesn't matter what you type in the separate window because it is not a valid stdin entry point. This makes sense, because when you pause the debugger and want to evaluate expressions, you use Komodo's debug output window. If we did not redirect stdin, you'd have to toggle between the separate window and Komodo when evaluating expressions.
