### ISSUE TITLE
markdown is missing from new file templates

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#15]

**Comment by Naatan** [comment]
I was gonna say it shouldnt have one because there really isnt a need for one, its like having a template for a text file.

Then I saw that we have a template for text files -.-

I don't really see the point for either, you shouldnt use the template feature if you're starting a blank file.

Then again if people wish to use the template feature for this, who are we to deny them. I still find it kinda silly though :p

**Comment by cgchoffman** [comment]
The alternate workflow is manually set the language for the file.  Personally, that breaks the workflow I have for opening everything single file I open in Komodo other than text files.  

Though I agree "text" shouldn't be in the templates.  We could be more creative with what is IN the MD template.  A link to githubs cheat sheet or something.
