### ISSUE TITLE
Ctrl+T not configured to insert snippet

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#1525]
### Short Summary
The [docs](http://docs.komodoide.com/Manual/abbreviations#abbreviations_inserting-snippets) say that Ctrl+T will insert an Abbreviation snippet, but it opens a new tab.

### Steps to Reproduce
Hit Ctrl+T at the end of an Abbreviation keyword.

### Expected results
The Abbreviation should get inserted.

### Actual results
A new tab opens.

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

### Additional Information
Changing the Prefs > Key Bindings for "Insert Abbreviation Snippet by Name" to Ctrl+T fixes (but then New Tab shortcut doesn't work, of course).

**Comment by cgchoffman** [comment]
FYI, as per @Naatan label change, this will be a docs change but I will also try to settle on an appropriate keybinding change, @hobbsd.  
Have you tried turning on "auto-abbreviations" for the snippet you want to insert?

**Comment by hobbsd** [comment]
I just tried using auto-abbreviations, which worked well, although I did have to turn off the popup event notifications, because they were appearing right on top of my snippet code.

**Comment by cgchoffman** [comment]
Is it different than this?  I believe that's an expected location.  
![screenshot 2016-05-18 12 44 31](https://cloud.githubusercontent.com/assets/655154/15372687/7ded5a1c-1cf6-11e6-811d-566ea208fdb1.png)

Having said that.  The reason we pop up the notification (and so in your face) is because there was a lot of confusion (and frustration) around abbreviations being injected into users code with no indication of what just happened. We needed to make it clear to users why Komodo just dumped code into their file.  With that in mind, the workflow is pretty much what you did; see the notification, acknowledge that you know what's going on, turn off notification if it's not needed or wanted.

**Comment by hobbsd** [comment]
Yes, it probably looked like that. Your explanation for it makes sense, and it was turned off easily enough, so it's not much of an issue.

**Comment by cgchoffman** [comment]
Thanks @hobbsd.  Thanks for bringing this to our attention.  FIxes incoming.

**Comment by cgchoffman** [comment]
Fixed with updated docs to suggest an updated workflow that works with more recent updates to Komodo since these docs were first written.
https://github.com/Komodo/komodo-docs/commit/efae3d6bcd7210e793e7d894a6cfe5df96a602d0
https://github.com/Komodo/komodo-docs/commit/63a77b1b98463250284e0b8527415715cd3fb036

**Comment by farkass** [comment]
Assigning Ctrl+T to "Insert Abbreviation Snippet by Name" is not a solution for me. 
Or at least it has a bug to leave the abbreviation in my text too just before the inserted value.
Using windows version 10.2.1 build 17670.

The "Auto-Abbreviation" option is working fine 
Unfortunately I have to check this option for my abbreviations manually one-by-one.
Is there a global option to use this for all the abbreviations?
Thanks!

**Comment by Naatan** [comment]
Just tried it myself, for me the abbreviation is replaced. Could you please open a new bug report? You're responding to a closed bug that's not related to your issue.
