### ISSUE TITLE
Interactive shell is editable

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1568]
### Short Summary

You can cut and paste content into the history above the input.  I believe this is a matter of setting "editable" in the view being used in that context.

**Comment by Naatan** [comment]
Wouldn't be that simple, given that this is also where you write your input.

**Comment by Naatan** [comment]
@mitchell-as should probably weigh in on this, if not be the assignee. I don't think this is a simple one to fix.

**Comment by mitchell-as** [comment]
Agreed, you'd have to have a "pre-insert" hook or something to check what line the text is being inserted on and accept or reject it. That is not trivial.

**Comment by Naatan** [comment]
Right, personally I am inclined to mark this as wontfix since it's a bit outside the scope of what we're trying to facilitate. If ever we implement a full terminal emulator then our REPL implementations could benefit from it, but until then I'd say this should just be a limitation.

Will let Carey close this if he agrees.

**Comment by cgchoffman** [comment]
HUh, i can't believe I didn't notice that in 9 but it's there.
