### ISSUE TITLE
Legacy Add-ons Dialog is Unreadable

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1606]
From OTRS:

### Short Summary

The Legacy Add-on's dialog, accessible from Tools > Add-ons (Legacy) is unreadable with the default theme.

### Steps to Reproduce

Tools > Add-ons (Legacy)

### Expected results

Legible dialog.

### Actual results

Illegible dialog.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Any

### Additional Information

Even though the legacy dialog is deprecated, it is accessible via the menu and should still work. OTRS user also reported the Commando version of add-ons manager is very unintuitive to use.

**Comment by Naatan** [comment]
Looks perfectly legible to me? 

http://screencloud.net/v/q7Gn

The only thing that's not legible is the selection on the left. But that's minor.

Reason I'm not making a big deal about the styling of this dialog is because it's legacy. It only serves as a fallback for those who really need it. It will not be maintained much further, if at all.

**Comment by mitchell-as** [comment]
![add-ons_manager](https://cloud.githubusercontent.com/assets/12902397/15545381/1dd0eee0-226a-11e6-8abe-a65b51d8be53.PNG)

The attached image is what I was supplied with.

**Comment by Naatan** [comment]
Ok. Honestly the dialog is there as a fallback for those who need it until I can fully deprecate it. Any of the time spend involved with this dialog should go into the new dialog and not the old dialog. So I'm going to mark this as won't fix, because the actual fix is to improve the functionalities of the new dialog. This one is marked legacy for a reason after all.
