### ISSUE TITLE
Setting non-default scaling factor in gnome/windows messes up Scintilla

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#162]
In gnome tweak tool I set my font scaling factor to 0.9, then I put my cursor on some text in Komodo and right click it, my selection will change to a line (or more) above.

@toddw-as any pointers?

**Comment by mitchell-as** [comment]
This is not a Scintilla issue, but likely an issue with how Komodo places the caret after a right click. You'll notice that Scintilla handles left-clicks and drags just fine. I'll look into this more.

**Comment by mitchell-as** [comment]
Scintilla is unaware that any font scaling is going on because its internal styles are not being updated. I suspect Gnome Tweak is doing some trickery behind the scenes to make Pango draw fonts larger than they actually are. Scintilla is completely oblivious to this and still things the font size is the same as when the style was last loaded. There is no fix for this.

**Comment by Naatan** [comment]
Unfortunately this is becoming more common and it's not something we can ignore. Whether Scintilla is aware of it or not; it is affected. We might have to patch Scintilla to have the awareness it needs, or provide a bandaid solution for the "effect" of the problem (the offset issue described).

**Comment by Mook-as** [comment]
We do [attempt to obey DPI settings](https://github.com/Komodo/KomodoEdit/blob/b750ff452ca750586d9d05b76f7ad28143b53d39/contrib/patches/scintilla/expose_dpi.patch#L70) on GTK; it would be useful to check if we're missing some of the logic there.  (Possibly hook up something to redo the value, similar to [what happens on Windows](https://github.com/Komodo/KomodoEdit/blob/b750ff452ca750586d9d05b76f7ad28143b53d39/contrib/scintilla/win32/ScintillaWin.cxx#L1241).)

**Comment by ervumlens** [comment]
I'm running into this problem, FWIW. Right-clicks moving me one line down and a few characters to the right. It only happens to me with the OpenBox window manager. Cinnamon and Xfce work fine.

I don't recall doing any tweaking other than to change themes (none of which seem to affect this problem for better or worse). OpenBox doesn't appear to use the settings in `gnome-tweak-tool` so I don't have a useful number to share here.

I haven't done enough right-clicking to notice the problem until now, but man it's a hard problem to work around when I need that click!

**Comment by ervumlens** [comment]
Some observations:

1. Left-click and middle-click always work as expected. 
2. The context menu itself is placed correctly.
3. All the values in [`ScintillaGTK::PressThis`](https://github.com/Komodo/KomodoEdit/blob/master/contrib/scintilla/gtk/ScintillaGTK.cxx#L1831) look fine for [`event->button == 3`](https://github.com/Komodo/KomodoEdit/blob/master/contrib/scintilla/gtk/ScintillaGTK.cxx#L1883). Specifically, the values related to [changing the selection](https://github.com/Komodo/KomodoEdit/blob/master/contrib/scintilla/gtk/ScintillaGTK.cxx#L1884-L1885) are correct. This means what I see on the screen is not coming from these values (although maybe it should).

Since everything looked fine down at the Scintilla level, I figured the problem was further along the message chain. 

To see if this was the case, I changed the right-click code's [`return FALSE`](https://github.com/Komodo/KomodoEdit/blob/master/contrib/scintilla/gtk/ScintillaGTK.cxx#L1894) to `return TRUE`. This would in theory stop the right-click message from propogating and instead use the correct values already calculated in `ScintillaGTK`. Magically the right-click worked as expected in OpenBox. Cinnamon and Xfce continued to work as expected. Change the code back and the problem in OpenBox returned. (I rebuilt and retested the code in both states many times, just to be sure it wasn't *actually* magic.)

I don't know what handles the button-press event after `ScintillaGTK`, but right now I'm blaming it for the problem. 

@naatan, my symptoms are similar to yours but I don't know if my underlying bug is the same. When you have time ("ha ha," right?), could you try building Komodo with the change I mentioned to see if it has any impact? If that doesn't help you, I'll move my problem to a new issue.

**Comment by ervumlens** [comment]
> I don't know if my underlying bug is the same... 

Now I think it's the same.

Font scaling breaks Komodo in Cinnamon for me, just as @naatan described. Like OpenBox, Cinnamon is not using values from `gnome-tweak-tool`, but Cinnamon does have its own font tweaking thing that includes font scaling. 

The patch/hack/proof-of-concept I made above fixes the font scaling problem here in Cinnamon.

--- 
In case you didn't notice already, the problem is worse as you right-click down the screen and as more lines are visible. The lines near the top of the screen aren't bad, but zoom out and right-click near the bottom and you're zipped up a bunch of lines.

**Comment by Naatan** [comment]
Very helpful @ervumlens, thank you so much! We'll be sure to look into this for one of our next releases.

**Comment by ervumlens** [comment]
"If the women don't find you handsome, they should at least find you handy." :muscle::neckbeard: 

More observations: 
4. Left-click is affected when attempting to drag-and-drop a selection. This operation fails where ever the right-click would jump lines. I only know this because... 
5. I [saw it in the `xul:scintilla` code](https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/bindings/scintilla.p.xml#L1515-L1523), next to \*bum bum BUM!\* [the code that's goofing up the right-click!] (https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/bindings/scintilla.p.xml#L1525-L1530) But `xul:scintilla` is merely a pawn for something more *sinister*, namely...
6. [The `scimoz_wrapper`] (https://github.com/Komodo/KomodoEdit/blob/b750ff452ca750586d9d05b76f7ad28143b53d39/src/SciMoz/scimoz_wrapper.template.js#L82-L83)! It wraps scimoz in *lies!* ... Okay, so Mook-as already said the problem was probably around the `logPixels` code. BUT! Remember I mentioned the values in `ScintillaGTK` always looked good no matter what the font-scale setting? It turns out `scimoz_wrapper` is *double dipping!* `ScintillaGTK` is *already* accounting for the font scaling. When `scimoz_wrapper` passes pre-scaled numbers to Scintilla, the results are overscaled!

Changing the font scale changes the values of `logPixelsX` and `logPixelsY`. But why does it usually work out okay in Linux? Because pre-scaling by 1 (96 logical pixels / 96 DPI) never overscales! `scimoz_wrapper` is an evil, twisted *genius!*

The *new* patch/hack/proof-of-concept. Replace this code in `scimoz_wrapper.template.js` (or, as I did, change the live `scimoz_wrapper.js` version under "mozilla/build/" if you don't want to rebuild anything) ...

```javascript
koSciMozWrapper.prototype.positionFromPoint = function(x, y) {
    return this.__scimoz.positionFromPoint(parseInt(x * this.logPixelsX / kDefaultDPI),
                                           parseInt(y * this.logPixelsY / kDefaultDPI));
};
```
... with this...

```javascript
koSciMozWrapper.prototype.positionFromPoint = function(x, y) {
    return this.__scimoz.positionFromPoint(x, y);
};
```

Now the wrapped scimoz scales the values itself, using some unknown process. I suspect Pango trickery here, as mitchell-as suggested.

This probably raises more questions than it answers, but I hope it helps narrow things down.

**Comment by ervumlens** [comment]
FYI, font scaling also affects the position of the auto-complete pop-up.

Font scale = 1.1
![small - autocomplete - 1 1](https://cloud.githubusercontent.com/assets/13005338/9204361/6ab6a964-4022-11e5-82c0-8817ae6e936b.png)

Font scale = 1.0 (normal)
![small - autocomplete - 1 0](https://cloud.githubusercontent.com/assets/13005338/9204360/6ab6633c-4022-11e5-9659-16722d249c59.png)

Font scale = 0.9
![small - autocomplete - 0 9](https://cloud.githubusercontent.com/assets/13005338/9204359/6ab2522e-4022-11e5-95c6-5d15a5d43c9f.png)

**Comment by arnoldbird** [comment]
Like ervumlens, I also was seeing the auto-complete popups misalligned.  Fixed by installing unity-tweak-tool and going to Fonts and clicking Restore Defaults.  This caused a lot of new spaces and tabs (I think) to be added to my open komodo docs.  However, when I closed komodo, and re-opened, that problem was gone.  I could then adjust the font size in the "color scheme" preferences in komodo, and all's well.  I'm using Ubuntu 15.04.

**Comment by mitchell-as** [comment]
Can anyone with a HiDPI screen on Linux verify the patch above works? You can test this on your current Komodo installation by searching for a file called "scimoz_wrapper.js" and modifying it. (Please make a backup first!) You just need to wrap that chunk of code in the test for non-Linux platforms.

**Comment by Defman21** [comment]
I'm not owning a HiDPI screen but I'm on Linux and this patch fixes autocomplete popup positioning for me when I'm using a non-standard FSF (Font Scaling Factor).

**Comment by bjmc** [comment]
I see this issue is closed, is there a good fix or workaround for this problem? Has the patch mentioned above been incorporated into a Komodo release? I'm still experiencing this with,

> Komodo Edit, version 10.2.1, build 17670, platform linux-x86_64.
> Built on Wed Mar 8 20:13:03 2017."

on Ubuntu 16.04 running the Gnome desktop environment on a HiDPI screen.

Here's an example of the problem in action, as you can see the autocomplete popup is displaced away from the line of active text:

![screenshot from 2017-03-29 13-39-59](https://cloud.githubusercontent.com/assets/328557/24454905/9c10fa4e-1485-11e7-92a2-e2661599a742.png)

**Comment by Naatan** [comment]
Could you open a new bug report and share your OS settings please? (anything related to resolution, HiDPI and font size).
