### ISSUE TITLE
file path missing from window title

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#1652]
### Short Summary

9.3 had a window title like "foobar.py (/work/yada/yada) Komodo IDE 9.3", 10 has just "foobar.py Komodo IDE 10.0"

Any chance to get that path back? I have lotsa files with the same filename...

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform linux-x86_64.
Built on Wed May 11 15:27:38 2016.

**Comment by mitchell-as** [comment]
Is this is with native window decorations on? I've turned mine on and I get the 9.3 window title style on my Linux box (Ubuntu 14.04 Unity WM).

**Comment by Naatan** [comment]
Note I think it strips the project path.

**Comment by agroszer** [comment]
It looks like this:
![screenshot_2016-06-03_08-08-10](https://cloud.githubusercontent.com/assets/350912/15770250/656870bc-2962-11e6-8d36-75ae5b10646d.png)

bootstrap.py is at /work/zopefix/zope.testrunner/bootstrap.py
places is open with the root ~/Dropbox/komodo/koctags
there is no open project

appearance looks like this:
![screenshot_2016-06-03_08-10-36](https://cloud.githubusercontent.com/assets/350912/15770280/b8a7d934-2962-11e6-8eda-8afc49ba0130.png)

**Comment by Naatan** [comment]
Ahh the screenshot is what I needed :) It doesn't show the full path because you are in trial mode. If you purchase Komodo and the trial message disappears your full path will show.

I guess technically the trial isn't "fully-featured" after all, this is the ONE "feature" that you will have to buy Komodo for .. :p
