### ISSUE TITLE
Komodo colorize this block not properly

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1677]
### Short Summary

```ruby
m.reply "Все получили #{value} #{lazuli_word value, {first: "лазулю",
                                                     second: "лазули",
                                                     third: "лазулей"}}"
m.reply "!add #{value} all"
```
![Imgur](http://i.imgur.com/MvJREDv.png)

**Comment by mitchell-as** [comment]
What language?

**Comment by Naatan** [comment]
Looks like either coffeescript or ruby.

**Comment by Defman21** [comment]
Ruby

**Comment by Defman21** [comment]
CoffeeScript does not recognize #{} properly, which is another issue. I'll file it.

**Comment by mitchell-as** [comment]
I thought it was Ruby, but I could not reproduce this, and I still cannot. I tried copy-paste and then typing out that last line.

**Comment by Defman21** [comment]
You won't be able to reproduce it with copy-pasting that.

**Comment by mitchell-as** [comment]
Well the ticket doesn't say I cannot :) Please describe how to reproduce the issue. Otherwise I won't be able to fix it.

**Comment by Defman21** [comment]
Type this code manually:
```ruby
puts "#{{test: 123,}}"
```

Next, press <kbd>Return</kbd> after `,`.

Then type `key: 456` and indent it like that:

```
puts "#{{test: 123,
         key: 426}}"
```

Add anything after this (`puts` for example):

```
puts "#{{test: 123,
         key: 426}}"

puts <- Komodo colorize it as a string
```

**Comment by Defman21** [comment]
Note:

If I do something like that:
```
puts "#{{test: 123,
         "key: 426}}"

puts
```
or 
```
puts "#{{test: 123,
         key: 426}}""

puts
```

The second `puts` colorizes as identifier (which is ok)

**Comment by Defman21** [comment]
Also inserting `""` after `test: 123,` and removing it fixes color of second `puts`.

**Comment by mitchell-as** [comment]
Confirmed. This is a bug with Scintilla's Ruby lexer. It doesn't handle multi-line interpolated code very well (to be honest, this seems quite rare in practice).

**Comment by mitchell-as** [comment]
After looking into this, I've determined it's really not worth the effort to try and patch Scintilla's Ruby lexer to be able to handle real-time multiline string interpolation.

Highlighting is already correct on a single pass from the beginning of the interpolation. This happens when copy-pasting multiline interpolations and modifying the document before a multiline interpolation. The only time this bug shows up is when you are currently editing a multiline interpolation.

This means the lexer does not keep track of interpolation on a per-line basis. Modifying it to do so would be far to complicated to justify handling this rare use case.

**Comment by Defman21** [comment]
Oh ok. I agree it's very rare practice so it wouldn't worth to implement that.
