### ISSUE TITLE
Go to definition don't work inside php docs/comments

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1754]
### Short Summary
The go to definition doesn't work inside (php docs) comments.

### Steps to Reproduce
Put a class inside a php doc en use the go to definition action.

### Expected results
Going to the definition

### Actual results
Nothing

### Platform Information
Komodo Ide 10 windows 10

**Comment by mitchell-as** [comment]
What does your "class inside a php doc" look like? Is it delimited in any special way? If not, then this is by design because then all words in comments are potentially classes and Ctrl+Hovering over them would be quite expensive in terms of trying to figure out what has a definition and what does not.

**Comment by Defman21** [comment]
I think he's talking about PHPDoc.

```php
/**
 * @var \path\to\MyClass (=> ./path/to/MyClass.php::MyClass::class) Description
*/
```

**Comment by babobski** [comment]
@Defman21 Thanks, Was talking about hte PHPDocs:
```php
/**
 * @var $var01 MyModal
 */
 
 /**  @var $var01 MyModal */
```

**Comment by Defman21** [comment]
Your PHPDocs are not valid. I don't see any reasons to parse this properly.

**Comment by mitchell-as** [comment]
Note to self: in fixing another goto definition bug, I discovered that goto definition intentionally does not work in strings and comments, so the hyperlink will no longer work in them.

**Comment by mitchell-as** [comment]
After more investigation, I'm going to mark this "by design". Codeintel intentionally ignores any comments, and changing it to not ignore comments if it is processing a "goto definition" request is a lot of work since all languages will have to be updated. All this work is for not much benefit -- especially due to Komodo X's new symbol browser. You should use that if you want to jump to your MyModel class.
