### ISSUE TITLE
Something in my file makes Komodo want to use 23 spaces per tab

### ISSUE THREAD

**Issue by mkimberling** [Komodo/KomodoEdit#1756]
### Short Summary
Komodo wants to use 23 spaces per tab with the attached file.  The problem goes away after I remove the "Allow file contents to override Tab and Indentation setting" check from Preferences.

### Steps to Reproduce
Open the attached file in Komodo 10 and observe 23 spaces per tab.

### Expected results
The settings in a file should not change how Komodo interprets the size of a tab.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1 build 89222
*Operating System (and version)?* Windows

 10

### Additional Information

before
![newfile](https://cloud.githubusercontent.com/assets/17583686/16425330/f4101166-3d18-11e6-96fc-0d6d9db8bb0d.png)

after
![saveastestdotpy](https://cloud.githubusercontent.com/assets/17583686/16425341/00bf917a-3d19-11e6-8b9c-568b5dcc63da.png)

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
@mkimberling I'm not seeing the attached file. Would you please reattach it? Thanks!

**Comment by mitchell-as** [comment]
Unfortunately github really likes to mangle e-mail responses. I'm not able to use your inline attachment. When you get the chance, please attach with a web browser. Sorry for all of this inconvenience :(

**Comment by mkimberling** [comment]
I am using a web browser.  Sorry but can you spell out exactly what I need to do to get you the attachment?

**Comment by Defman21** [comment]
You're replying using your mail (Yahoo mail?). Use Github instead https://github.com/Komodo/KomodoEdit/issues/1756

**Comment by mkimberling** [comment]
i did last time.  I'm on the Git page now.

**Comment by Defman21** [comment]
Now attach a file as @mitchell-as required.

**Comment by mkimberling** [comment]
And how does one do that?

**Comment by mkimberling** [comment]
[test.txt](https://github.com/Komodo/KomodoEdit/files/337688/test.txt)

**Comment by mkimberling** [comment]
Renaming the file to .txt worked.

**Comment by mitchell-as** [comment]
Thanks, I also get a really big indentation default. I'll look into this.

**Comment by Defman21** [comment]
I probably know what's going on there. As you can see Mitchell, the first "indent" is 6 tabs. Komodo probably recognize that as one tab and then make the indent width: `width of the first indent * width of tabs`. `6 * 4 = 24`. And if you forgot, `require('ko/editor').scimoz().indent` returned 23 (0 seems to be a "legit" indent) in this file.

**Comment by Defman21** [comment]
Here's an example file with this behavior being fixed:

[test.txt](https://github.com/Komodo/KomodoEdit/files/337770/test.txt)

```diff
--- test.txt	2016-06-28 21:25:52.087558498 +0300
+++ test.txt    2016-06-28 21:25:06.693058785 +0300
@@ -4,7 +4,7 @@
 import serverdb as serverdb
 from sqlalchemy import and_, not_, literal
 from sqlalchemy.sql import functions, func
-
+	
 import rat.ratcumulusutil as ratcumulusutil
 import sqlalchemy
 import time as _time
```

**Comment by mitchell-as** [comment]
Thanks @Defman21 you are correct that the first, massive indent level is throwing things off.

@mkimberling When it comes to "allow file contents to override indentation settings", we just look for changes in indentation starting from the first line. It's really not more complicated than that. Your file has 6 consecutive lines with 5 tabs + 3 spaces as the "first" level of indentation seen in the file. This caused Komodo to think one level of indentation is 23 spaces (5 tabs @ 4 spaces/tab + 3 spaces = 23).

In this case, you'd go to Edit > Current File Preferences for your particular file, uncheck "Allow file contents to override ...", click Apply, and then re-open the file to get your 4 space indentation. That setting will only apply to the current file. Any other files you open will still have "Allow file contents to override ..." checked.

I'm going to mark this ticket "by design" and close.

**Comment by mkimberling** [comment]
Thanks for your help getting to the bottom of this.  I'm not sure why this code was indented like that but I never would have guessed that this feature would work that way.

**Comment by tonyattwood** [comment]
Hey,

We've  finnaly got home and wanted to share some cool pics of our  journey, just  take a  look <http://follow.refinancehow.com/e4evuw>


Sincerely, tony.attwood@ntlworld.com

**Comment by Defman21** [comment]
Actually, I disagree with this design. You're checking for [300 lines](https://github.com/Komodo/Komodoedit/blob/master//src/languages/koLanguageServiceBase.py#L3285) (thanks to Carey for pointing that to me) to detect spaces or tabs (based on the amount of them in the file). Why not checking which space width number is the most popular in the file rather than using the first indentation? So in case someone indents their 8-line config variable with 8 spaces and 280 lines of code with 4 spaces, their indent char will be 4 chars. If it's too complicated to implement then okay that's not that important :)

**Comment by Naatan** [comment]
I'm with Defman on this, but this isn't the place for it. @Defman21 wanna file a new bug? :)

**Comment by Defman21** [comment]
Yeah sure.
