### ISSUE TITLE
"Replace All" and "Find All" do not work as expected

### ISSUE THREAD

**Issue by ginocappelli** [Komodo/KomodoEdit#180]
Hi there, I think that I found some bugs in version 9.0.0 of Komodo Edit. 

1st Issue: When I right-click on the project name and select "Replace..." the dialog window that opens do not contain the "Replace All" button, I therefore have to click two times on the "Replace" checkbox in order to show up that button.

2nd Issue: In the same dialog, when I put some text in the "Find what:" input field, and I search for replacements in the whole project directory (Using "Match case") the program does not find any occurrence, whilst thare are many of them (previous version of Komodo Edit worked fine).

3rd Issue: THIS IS NOT AN ISSUE but I take this opportunity to suggest an improvement to the "Replace All" behaviour: When I search a large project I have to wait until the IDE has fetched all the folders before I can click the "Make Changes" button. But sometime I am fine and I would like to stop the fetching and just replace the occurrences that the IDE has found up to that point.

Hope this helps,
Gino Cappelli

**Comment by Naatan** [comment]
Already fixed with #79. Please try the nightly.

**Comment by cgchoffman** [comment]
For number 3:  it sounds like you need to narrow the scope of your search to the folder you care about rather than searching your whole project.  Though it couldn't hurt to eventually allow a user to top a search and work with what you've found so far.  File that as a separate enhancement request.  Please don't file 3 reports in one issue.  Thanks for using Komodo!
