### ISSUE TITLE
No access to menu on focus mode on Ubuntu (Unity)

### ISSUE THREAD

**Issue by krychu90** [Komodo/KomodoEdit#1804]
### Short Summary
When you turn on focus mode then you have no access to menu. Alt key is restricted to Unity command search (no integrated with Komodo menu).

### Steps to Reproduce
- Turn Focus mode
- Try to get access to menu (ALT key)

### Expected results
Other key (or icon) should give access to the menu

### Actual results
No access to menu.

### Platform Information

*Komodo Edit* 
*Komodo Version 10.0.1* 
*Operating System Ubuntu 16.04*

**Comment by mitchell-as** [comment]
Hi, when you are not in focus mode does Alt gives access to the menu? If not, then focus mode is not really the culprit here. Do you have native window decorations enabled or disabled? If they are disabled, when you toggle focus mode, at the top right of the titlebar should be two icons: toggle focus mode and the hamburger menu. The hamburger menu icon gives access to Komodo's menu. If you have native window decorations enabled, you'll have to do "View > Toolbars > Show Menubar" before entering focus mode. Then your menubar should always be visible.

**Comment by Defman21** [comment]
This is actually a good point IMO and it could be resolved by merging this PR:
https://github.com/Komodo/KomodoEdit/pull/868

So you'll have your menu in Unity statusbar.

**Comment by krychu90** [comment]
Hi,
i forgot that i have enabled native window borders option.

>  If you have native window decorations enabled, you'll have to do "View > Toolbars > Show Menubar" before entering focus mode. Then your menubar should always be visible.

Yes, for now this is the only option (if you know that you have to enable menubar before enable focus mode).

**Previews**:
Focus mode off
![focus mode off](https://cloud.githubusercontent.com/assets/11661487/16868372/90ddc568-4a77-11e6-9133-21d978b61983.png)

Focus mode on
![focus mode on](https://cloud.githubusercontent.com/assets/11661487/16868383/a0cad6b4-4a77-11e6-8902-e241c4d97fcd.png)

After press alt key on focus mode
![focus mode on alt](https://cloud.githubusercontent.com/assets/11661487/16868401/b038de52-4a77-11e6-99cf-d9315971a512.png)

**Comment by mitchell-as** [comment]
Yeah, it's an unfortunate workaround for now until we address #868, which appears to be back on the table. I'm going to close this ticket in favor of #868.
