### ISSUE TITLE
Unable to save file to disk.

### ISSUE THREAD

**Issue by rfoxmich** [Komodo/KomodoEdit#1805]
### Short Summary

Saving a file I'm editing has lately started to fail.  Here is the error dialog text:

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1293"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.isEncodable]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: _validateEncoding :: line 1293"  data: no]

Traceback:
_validateEncoding@vieweditor:1293:16
save@vieweditor:1390:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1904:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:8
command_doCommand@chrome://komodo/content/library/commands.js:230:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:187:12

Komodo IDE, version 9.2.1, build 87651.
Built on Tue Sep 01 17:19:15 2015.
### Steps to Reproduce

Work on  a fairly large docbook documentation file (about 20K lines of text)
### Expected results

The file would be saved to disk.
### Actual results

Dialog described above is emitted.
### Platform Information

See above for komodo ide.
Windows 7 professional service pack 1.
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

Exit komodo and restart it works for a while but eventually fails again.

**Comment by mitchell-as** [comment]
Hi, it is highly likely that your document contains characters that are not in the file's encoding. What file encoding are you using? UTF-8? Are you cutting and pasting characters from an outside source? Some applications are not UTF-8 aware and can end up putting extended ascii characters on the clipboard, for example.

**Comment by rfoxmich** [comment]
UTF-8 with unix line endings.  How would I find such characters (illegal UTF-8)?  
Why should having them kill the save in such a nasty way -- sometimes but not all the time?

What I did do is cut the file into two chunks I did not (yet) see this rear its ugly head again.  If you are correct, then it could be that the chunk I was editing did not have offending characters.

**Comment by rfoxmich** [comment]
Following http://stackoverflow.com/questions/115210/utf-8-validation  I ran iconv to look for invalid utf-8 in both slices of my file and there were no error messages.  
  Is Komodo IDE well behaved when it starts to run out of virtual memory?  The total length of both files is 828877 bytes as gotten by the unix wc utility.

**Comment by mitchell-as** [comment]
Before saving to disk Komodo likes to check that the characters in the file are consistent with the file's encoding. This ensures any UTF-8 aware program can open and read that file. I agree it's a nasty looking error, but that's what we have for now. When attempting to find the offending character, the error message later down might mention a "UnicodeEncodeError" or "UnicodeDecodeError" that happens at a particular character position. That may help. Otherwise, your method of splitting up the document into chunks and trying to find the offending chunk will probably be sufficient.

As for why this happens sometimes, but not all the time, I cannot say because I don't know your "save flow", but I'd venture a guess it happens only when you have invalid UTF-8 characters in the document.

**Comment by mitchell-as** [comment]
Yes, running iconv on your file shouldn't yield any errors because Komodo shouldn't save an invalid UTF-8 file. If you could run iconv on the stream of text Komodo refuses to save, that would be another matter :)
