### ISSUE TITLE
Confirm Replacements dialog is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1833]
### Short Summary

When you search & replace in a directory, you'll get this dialog that will you ask to confirm replacements. It's a bit broken.

If there are files without an extension, you're not able to check/uncheck them.

If there are files without an extension and no changes will be made to them,  they are showing on Confirm Replacements dialog (files with extensions are hidden).

**Comment by cgchoffman** [comment]
Screen shot please.  Pretty sure this is by design.  Does it say "skipped" and "unknown Language" beside those "broken" entries?

**Comment by Defman21** [comment]
Will do. This is not by design, trust me :P

**Comment by Defman21** [comment]
![Imgur](http://i.imgur.com/B9nPuxi.jpg)

**Comment by cgchoffman** [comment]
Yes unfortunately, as I said, this is by design.  It was meant as a save guard to not allow editting of binary files I believe.  See #467.

**Comment by Defman21** [comment]
What's the point of displaying a check mark? :)

**Comment by cgchoffman** [comment]
I don't know what you're talking about.  You reported two issue in your original comment and they are addressed by #467.  Is there another issue?

**Comment by Defman21** [comment]
Do you see a checkbox? There's a check mark right behind it. I think it should not be visible in this way.

**Comment by cgchoffman** [comment]
Ahh, no that's supposed to be there.  That's the XUL treeview indicator that the column is a checkbox column.  Looks like the CSS is bad for the dialog though as the selection (if that's a selection) covers part of the checkmark. You COULD file a new bug for that but I wouldn't bother.  That dialog will get an overhaul when it's UX get's fixed in #467.

Here's the same checkmark in the Publishing dialog.
![capture](https://cloud.githubusercontent.com/assets/655154/17003077/2bc14686-4e83-11e6-9bba-cb776599c6ce.PNG)

**Comment by Defman21** [comment]
This one looks cool! (btw this is how the checkboxes I showed looks like where there are files where the replacement can be)

**Comment by Defman21** [comment]
![Imgur](http://i.imgur.com/tWF7REc.png)

**Comment by cgchoffman** [comment]
ya there is some weird styling going on there that's causing the check mark to get covered.  I suspect that if the `hello.php` item was the first in the list then the checkmark at the top wouldn't be covered any more.  As I said, that probably won't make it through an overhaul of the UI and UX of that dialog.
