### ISSUE TITLE
Workspace Restore — Yes should be before No

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1941]
The image says is all
http://i.imgur.com/awQromy.png

**Comment by srgloureiro** [comment]
BTW, I noticed it is disseminated in every message box the 'Yes' being the last option, which does not make any sense to me.

**Comment by srgloureiro** [comment]
http://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right

**Comment by Naatan** [comment]
I agree from my personal perspective it makes more logical sense to put OK before Cancel, but I think the general UX has become the reverse. Why? I'm not sure, probably some dev ages ago making a UX decision which should have been deferred to a UX designer (which at the time likely wasn't a thing yet), and it has since just become a standard. I don't feel like an IDE is the application to pioneer a change in this area, we'd have to look to the platforms (Windows, Linux, .. ) for that.

**Comment by srgloureiro** [comment]
Perhaps because in the keyboard the Esc is before the Enter?

**Comment by cgchoffman** [comment]
> Perhaps because in the keyboard the Esc is before the Enter?

Not if your mother tongue is Hebrew, Arabic, or Syriac.
