### ISSUE TITLE
Komodo Edit Update Failed

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#196]
The update from 9.0 to 9.0.1 failed with this message: "The integrity of the update could not be verified." This happened on both of my Win7 machines.

**Comment by cgchoffman** [comment]
I've tested this on a few different machines and can't reproduce.  Update installs cleanly.  What version are you updating from?  Help > About Komodo

**Comment by hobbsd** [comment]
In both cases I was updating from the release version of 9.0, which is no longer installed so I don't have access to the specific build info. On the first machine Komodo informed me of the update, and I gave it the go ahead; on the other I ran "Check for Updates". In both cases Komodo first downloaded a small file that failed integrity checks, then a large file that also failed.

**Comment by Naatan** [comment]
Please make note of your build number when next you update and let us know if the problem happens again (including the noted build number).

**Comment by we3geeks** [comment]
See attached. 

Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

![4_23_15__7_24_pm](https://cloud.githubusercontent.com/assets/2390335/7310778/1549ee02-e9ef-11e4-9544-fbfb6e339e79.png)

I have not yet updated, so if there is information you need from my box before I update, please let me know?

**Comment by Naatan** [comment]
@we3geeks why are you using Komodo Edit? :p

**Comment by testworksau** [comment]
I am using Komodo Edit with Windows 8.1, same issue.

**Comment by we3geeks** [comment]
@Naatan Sigh. Been crazy busy these past couple weeks and just now getting back to a point where I can switch back to IDE on this box. :/

I didn't think much about it until this happened on my box at home this evening, but when I updated my v9 IDE (yes, IDE :smile:) install at work yesterday, it encountered some sort of error with the update, but it went ahead and downloaded the 9.0.1 install and installed it on its own, then restarted.

Offer still stands: if there is anything you need to know from this box to troubleshoot, ping me. (But I will actually get my v9 IDE license installed, I promise.)

**Comment by ashmigelski** [comment]
Same issue for me

Komodo Edit, version 9.0.0, build 15707, platform linux-x86_64.
Built on Thu Mar 19 06:35:26 2015.

**Comment by cgchoffman** [comment]
Hey all, thank you for reporting this.  The issue is due to incorrect checksums for the Edit bits.  Please don't update for now, that includes using the installer.  They are most likely fine but better to be safe then sorry.  The [latest nighlty](http://downloads.activestate.com/Komodo/nightly/komodoedit/latest-9.0.1/) should have a significant portion of the fixes that went into 9.0.1.  Please use that for now.  We're looking into the issue and will have it resolve ASAP so you can update.

FYI, IDE bits are fine to use..

**Comment by cgchoffman** [comment]
Apologies for this issue folks.  Please run updates again.  The issue has been resolved.

**Comment by we3geeks** [comment]
Saw this same issue updating Edit to 9.1.0 on one of my OS X systems this evening...

**Comment by cgchoffman** [comment]
That is not the same issue.  The update wouldn't not work at all if it was the same issue.  I've confirmed that checksums on the update bits are correct just to be safe and this was tested on OSX before release.  When Komodo downloads the full update that usually means that something has been modified in your install directory since you installed.  I'm sorry you had to wait for the full automatic update to occur but sometimes that happens.

**Comment by we3geeks** [comment]
@cgchoffman Thanks for the follow-up. Sorry, that was an assumption on my part that the same symptoms were indicative of the same issue. What sorts of things being changed within the install directory would lead to this? I ask because I've not -- to the best of my knowledge -- touched anything within the install directory.

**Comment by cgchoffman** [comment]
hey lets move this to #321.  Didn't see that you had looked at the logs already.  Hopefully you were looking at the wrong logs :)  

To answer your question, partial updates attempt to apply a series of patches to your Komodo install.  If any of those patches fail then it applies the full update.  I'll have to see the update logs to see why that might fail.
