### ISSUE TITLE
Komodo does not kill processes ran with shell.run()

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1983]
### Short Summary

For example, run `middleman server` via `shell.run()`. Then close Komodo. middleman server will still stay open. Komodo should kill this process.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1 nightly
*Operating System (and version)?* Ubuntu 16.04

**Comment by mitchell-as** [comment]
I would argue this is expected behavior. `shell.run()` ultimately calls `require('sdk/system/child_process').spawn()`. Any time you spawn an asynchronous process, it is expected to survive after the parent. For example, the codeintel process is spawned and has to be forcibly killed upon Komodo exit; it would live on otherwise. Since `shell.run()` returns the process, so you are expected to kill it on Komodo exit if that's what you desire. (I assume you are running it yourself since I don't see Komodo mis-managing its `shell.run()` calls.)

**Comment by Defman21** [comment]
It makes everything much complicated. Now I have to listen to close event (and, if Komodo will crash, these processes will still there) and store processes somewhere to kill them. I'd want to suggest a new option for `shell.run()` which allows you to run processes that will be killed on Komodo close.  Would it worth it?

**Comment by Naatan** [comment]
You could try playing with the `detached` option: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by Defman21** [comment]
Thanks!
