### ISSUE TITLE
Active tab indication

### ISSUE THREAD

**Issue by bitman** [Komodo/KomodoEdit#200]
Can it be made more obvious which tab is the current one being edited? I see it's currently bolder with a thin border. Maybe an option to select the background tab colors in the color scheme would help.

**Comment by Naatan** [comment]
What OS are you using? Can you post a screenshot?

**Comment by bitman** [comment]
Using Windows 7

Here the active tab is test4,pl, with many tabs open it becomes increasing difficult to hone in on the one you're looking at.

![screenshot 2015-04-23 17 24 24](https://cloud.githubusercontent.com/assets/225277/7301978/ff70fd84-e9dd-11e4-9773-776ada4458ce.png)

**Comment by Naatan** [comment]
I'm confused, the active tab is indicated by:

 * a contrasting font color (black instead of grey)
 * a contrasting background color (lighter)
 * a border around the tab

Do these things not stand out on your monitor? If it's just not enough then I would recommend using something like Stylish, I don't want to make the tab contrast too strong that it essentially becomes a big red button on the screen.

I do hear your concern but as you are the only one that has expressed it so far I have to wonder whether this is a subjective issue that does not affect many people besides yourself.

**Comment by bitman** [comment]
Fair enough. I'm old. :)
