### ISSUE TITLE
Link to spec for CodeIntel is dead

### ISSUE THREAD

**Issue by jeteon** [Komodo/KomodoEdit#201]
In the file [_codeintel2/__init__.py_](https://github.com/Komodo/KomodoEdit/blob/master/src/codeintel/lib/codeintel2/__init__.py) reference is made to a specification for the Code Intel system which is supposed to be hosted at http://specs.tl.activestate.com/kd/kd-0100.html. This link is dead, however. Would it be possible to update the link to where the spec currently lives?

I have been working with the Code Intel code-base for some time now and believe both myself and others who have to interact with it in future, would find it helpful to have a non-code document describing this rather complex system.

**Comment by Naatan** [comment]
The link you're referring to is an internal link. You make a fair point though, and we'll definitely be looking at exporting some of that documentation. I'm closing this issue because its not directly related to Komodo (the application) itself, but rest assured we will be looking into this.

By the way, if you're interested in working on codeintel and like getting paid, check out our job opening - http://www.activestate.com/company/careers/komodo-mozilla-python-web-developer

;)

**Comment by jeteon** [comment]
Thank you for looking into this issue as well as letting me know about the job opportunity.

**Comment by jeteon** [comment]
Hi @Naatan. Have you heard anything with regards to the potential for exporting some of the internal documentation you have?

**Comment by Naatan** [comment]
First step will be getting our new documentation site up and running, once that's done we can look further into this.
