### ISSUE TITLE
Vim two single quotes command does not work

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#2027]
### Short Summary

Vim two single quotes command does not work

### Steps to Reproduce

- from the current line move with a Vim command
- press single quote two times to return to previous line

### Expected results

it should return to previous line

### Actual results

most of times it goes somewhere else, often to the beginning of current line

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* <Komodo IDE, version 10.1.1, build 89474, platform win32-x86. Built on Thu Sep 01 14:27:01 2016.
*Operating System (and version)?* Windows 8.1

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment]
Reproduced.

**Comment by mitchell-as** [comment]
After looking into it, this appears to be by design. The `' '` command uses Komodo's history feature to jump back to the previously jumped to line. I'm not too familiar with this history feature, but I'm pretty sure it would be unwise to record every movement to the history. That would render the back/forward navigation buttons pretty useless.
