### ISSUE TITLE
Jumpy Minimap scrolling

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#2080]
### Short Summary

When I grab the minimap "drag bar" outside some sweet spot near its vmiddle, the editing window seems to snap to some position near the vmiddle of the drag bar as soon as I start to drag it.

When I release dragging, the editor window snaps (moves) some number of lines up or down from the position where I released dragging.
### Steps to Reproduce
1. Open a file that's longer than, say, two screens.
2. Scroll down so the top of the file is out-of view
3. Position pointer near the top of the minimap drag bar
4. Drag down.
### Expected results

Smooth scrolling.
### Actual results

I often find myself lost after I release the drag.

End-result is a jumpy scroll in the main editing window.  I think I know where I want to work, but it snaps away when I release.
### Platform Information

Komodo IDE, version 10.1.1, build 89474, platform win32-x86.
Built on Thu Sep 01 14:27:01 2016.
### Additional Information

Apologies in advance for the looping GIF.

At the beginning, I grab the drag bar near its top and very slowly drag down.  You can see the viewport jump to the top of the file as the pointer moves down.  It reverses course when the pointer gets near the middle.

Then, near the end, I release and the viewport jumps a few lines.  OK, the gif shows it jump one line.  The release jump seems worse on longer files (or it might be my imagination).

![minimap](https://cloud.githubusercontent.com/assets/13684992/19017371/f05ab846-87eb-11e6-9605-76975c1dcaec.gif)

**Comment by babobski** [comment]
Tested it and got it confirmed.
If I scroll to the bottom of my file and try to scroll down on the mini map I will end up at the top of my file.
Made a [screencast](http://youtu.be/whgtOpDrNOE?hd=1) to show the issue.

## Platform Information
Komodo IDE 10.1.1 build 89474 (platform win32-x86)

**Comment by mitchell-as** [comment]
Thanks for the report.
Note to self: The minimap XUL bindings are probably the place to look.

**Comment by Naatan** [comment]
Note the last line seems to be highlighted in a different shade from the rest of the minimap highlight.

**Comment by mitchell-as** [comment]
The fix I committed reduces the jumpiness and disorientation, but it's not perfect. There will be a larger jump the further away you click from the center.

The underlying issue appears to be by design in order to ensure that when you click+drag to scroll to the top of the minimap, you are at the beginning of the document, and when you click+drag to scroll to the bottom of the minimap, you are at the end of the document. If I were to try to keep track of the click+drag offset like a normal scrollbar, in certain circumstances by the time you reached either end of the minimap, you wouldn't be at document/start end.
