### ISSUE TITLE
View log File not working

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#221]
Menu 
Help > Troubleshooting > View Log File 
is not working

**Comment by cgchoffman** [comment]
I"m not able to reproduce this.  Can you try resizing the logs dialog?  Also, please retrieve the logs manually and copy them here in a gist or a code section.  I believe you're on Windows so you can find the logs in C:\Users\YOU\AppData\Local\ActiveState\KomodoIDE\9.0\pystderr.log

**Comment by cgchoffman** [comment]
@srgloureiro what platform are you on?  I just noticed this on Windows but it's just scrolled down.  If  you scroll up the logs are there.

This is because I have preferences > Editor > Scrolling: Enable scrolling past the end of the buffer.  

Looks like we're getting a little eager about showing you the end of the file.  Could you please confirm my findings so I can update the bug appropriately?

**Comment by srgloureiro** [comment]
I am on Windows, but I am not seeing the bug now. May be it was been fixed with the upgrade to 9.0.1 or when I reported its window got displayed behind another window.

**Comment by cgchoffman** [comment]
Ok. It's not clear from your initial report what happened.  Could you provide more details in the future?  Eg. What you did, what you expect to happen/see, what actually happen.
