### ISSUE TITLE
On focus don't check file status if other window is a Komodo Window

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2283]
When I focus from a other aplication in Komodo it does an file status check, when I switch between two Komodo windows the behavior is the same. This can be very annoying when you have to switch between the komodo windows. Switching between the two komodo windows feel buggy especially when you have a lot files open in one of th komdo windows. It hangs for a few seconds before I can do something.

### Steps to Reproduce
Open two komodo windows both on remote, and in one of the windows have 10+ files open.
Swtich between the windows.

### Expected results
Switvhing between the two windows should be smooth.

### Actual results
Komodo hangs a few seconds between switching between the two komdo windows.

### Platform Information
Windows 10 Komodo Ide 10.1.4
 
On focus don't check file status if other window is from Komodo

**Comment by Naatan** [comment]
The core issue here is that remote files are handled synchronously. We will be working on a fix for this soon. The suggested fix here is a workaround and one that would be difficult to do since we cannot check what application last had focus. At best we could do something with timers which is not ideal.

Rest assured the core issue here will be resolved.

**Comment by babobski** [comment]
Ok, Thanks for the explanation.
