### ISSUE TITLE
The issue about the location of caret in all input fields of save file dialog

### ISSUE THREAD

**Issue by danny-su** [Komodo/KomodoEdit#237]
My OS is Windows 8.1 x64, and used Komodo IDE 9.0.1.

**Comment by Naatan** [comment]
Carey, what's this? :p

**Comment by cgchoffman** [comment]
Why it's the issue about the location of caret in all input fields of the save file dialog.  This has been around.  There is a report in bugzilla already but as far as I know there was never any work done on it.  

To repro:
- using Windows >= 7 
- open a new file (eg text-1.txt)
- ctrl (cmd) + s to save

You'll see that the caret appears to be at 8 characters into the default file name.  No matter where you move the ACTUAL caret, it will appear to pop back to the 8th character position each flash.

**Comment by mitchell-as** [comment]
This is most definately a Mozilla/XUL issue. While it's a nuisance, it's not a showstopper because you can still type where you want in the fields -- the caret just doesn't accurately reflect the current position.

Moving to backlog.

**Comment by mitchell-as** [comment]
Strangely enough, this may be affected by the current caret position in the document.

1. If the caret is at the beginning of the document, the caret in the dialog will remain in the first position.
2. If the caret is in the first X positions in the document, where X is less than or equal to the length of the initial filename in the save dialog, then the caret will remain at position X.
3. If the caret is beyond X as described above, this glitch will not happen.

I may be wrong, but I seem to recall this when I investigated last month. It was quite peculiar.

**Comment by cgchoffman** [comment]
I'm not seeing exactly the same symptoms as you Mitchell but it's definitely related to the position of the caret in the file.  I created a gif (that I hope works) to show what I'm seeing.  For any one interested I used LICEcap.  It's pretty handy.
![bookies](https://cloud.githubusercontent.com/assets/655154/11429622/853eb266-942f-11e5-8d85-b7f827758e87.gif)

**Comment by demanl** [comment]
this problem is quite annoying.  it makes seeing where the cursor is located in the save dialog filename box very difficult to view.

this bug is very visible.  everyone who trys this editor on windows will see it within the first hour of using komodo.  it could lead the user in feeling un-comfortable with the quality of the editor in general.

and if you cannot fix the simple things......how are you going to handle the difficult ones......

a mature product such as komodo should NOT have a bug as visible as this one is EXIST for as long as it has.    You need to PROTECT komodo image and fix this very visible bug quickly.

tyia for the hard work that has gone into this project.

**Comment by mitchell-as** [comment]
Sorry, I cannot justify the time spent on finding a Windows-specific Mozilla patch that fixes this, rebuilding Mozilla, etc. at this time. So far, only two people have commented on this minor inconvenience. Closing this ticket.
