### ISSUE TITLE
Tab Context Menu - Publishing 

### ISSUE THREAD

**Issue by ncwcjim** [Komodo/KomodoEdit#2422]
### Short Summary
Updating to 10.2.x the Tab Context Menu - Publishing / Push / Diff selections are always greyed out; 10.1.4 does not have this problem

### Steps to Reproduce
Open a project; select a file; alt-click on the tab; select Publishing

Both Push and Diff selections are greyed out

### Expected results
Diff should show differences between load and remote files; Push should copy the file to the remove host

### Actual results
Nothing; selections are greyed out

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.0/10.2.1
*Operating System (and version)?* 
Windows 7

**Comment by cgchoffman** [comment]
Sorry, I thought I had closed and comments on this ticket. @ncwcjim your report is a duplicate of #2369 which will be fixed in the next nightly build and the subsequent 10.2.2 release.

The fixed nightly will be here: http://downloads.activestate.com/Komodo/nightly/komodoide/latest-10.2.x/ around 12:30 pm PST.  Confirm the build number is 89870 before testing.
