### ISSUE TITLE
Unable to add a file to a project by double clicking the template option

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2568]
### Short Summary

When a user tries to add a file to a project, a file is created automatically when user double-clicks on File template option. Komodo throws error mentioning "Can't associate a non-disk file with a project". There are two issues here:

1. A file created by double-clicking the template should be added to the project else user should NOT be able to create a file without specifying a filename.

2. Error message when a file is created is not helpful. It should be re-worded.

### Steps to Reproduce
1. Select Project menu > New Project.
2. Use the dialog box to navigate to your project folder and name the project file, and then click Save.
3. Right click on the project in the projects pane
4. Click Add -> New File
5. Double click on a template

### Expected results
A file should be added to the project
or 
User should be notified for specifying a file name

### Actual results
1. A file is not added to the project 

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2.2
*Operating System (and version)?* macOS

### Additional Information
1. File creation dialog

![image](https://cloud.githubusercontent.com/assets/26605593/25641525/6669d698-2f49-11e7-9b6c-cd1be7c4872b.png)

2. Error message

![image](https://cloud.githubusercontent.com/assets/26605593/25641535/7517b91c-2f49-11e7-85ea-509cb6da2307.png)

**Comment by cgchoffman** [comment]
It looks like this is half fixed in Komodo 11.  That workflow opens the file template system which @Naatan has redone to open in Commando.  When you select a file from this new interface it asks you to give it a filename before it creates the file.  That's as far as the workflow fix goes though.

The file is NOT added to the project and you still get the Error message that should be reworded.

Looks like we just need to figure out why creating file fails to get a path to the "add new file" function in your project and we should be good.

**Comment by cgchoffman** [comment]
To clarify, you can't add a new file to a project AT ALL any more with the new template system.

**Comment by cgchoffman** [comment]
Closing this in favour of https://github.com/Komodo/KomodoEdit/issues/2569
