### ISSUE TITLE
basename() returns file path and not filename

### ISSUE THREAD

**Issue by mjross** [Komodo/KomodoEdit#2687]
### Summary
The [documentation for basename()](http://docs.komodoide.com/SDK/api/commonjs/file#ko-file_methods_basename) states that it returns the name of the file when given a file path, but all of my testing indicates that it instead returns the full file path, e.g.,
`alert( require("ko/file").basename("/foo/bar/baz") );`
produces the message `/foo/bar/baz`, not `baz`.

Also, the method name basename() is misleading, because the base name of a file is the filename without any extension, e.g., the base name of `baz.txt` is `baz` -- i.e., it is not necessarily the full filename.

### Platform Information
Komodo IDE 10.2.2 on Windows 10 Pro

**Comment by mitchell-as** [comment]
Hi, that's odd. I cannot reproduce this, but I'm on Linux. In my Console (bottom pane), I entered

`require('ko/file').basename('/foo/bar/baz');`

and 

`baz`

was returned. @cgchoffman can you reproduce this on Windows? @mjross what happens if you replace the `/` in your string with `\\`? (Note the two `\\`s needed to produce one `\`.)

**Comment by mjross** [comment]
Hello, everyone. That's a good idea. I should've thought of that. It turns out that your hunch was correct, and the use of backslashes fixed the problem. Perhaps the documentation for that method could be updated to remind people that they need to keep that distinction in mind as to the formatting of file and directory paths?

**Comment by Naatan** [comment]
We should fix this in our SDK. Or rather, implement this in our SDK. iirc atm it just defers to Mozilla's file SDK, which is terrible.
