### ISSUE TITLE
Cannot drag window in OS X 10.12.6

### ISSUE THREAD

**Issue by doughemi** [Komodo/KomodoEdit#2703]
### Short Summary
Cannot drag window when I click and drag in title bar

### Steps to Reproduce
Open application

### Expected results
Window can be dragged on screen

### Actual results
Window cannot be dragged.

### Platform Information

*Komodo Edit
*Komodo Version? version 9.3.2, build 16484
OS X 10.12.6

migrated to iMac 21.5" 4K Retina from 2009 iMac running OS X 10.11.6. Works fine on El Capitan.

**Comment by Naatan** [comment]
Where are you clicking on the titlebar?

**Comment by doughemi** [comment]
Anywhere in the title bar above the icons. This works fine on my El Capitan iMac, but does not on Sierra. OS windows will drag when clicking anywhere in the gray portion of the window header, but I realize this is not necessarily true of application windows.

—Doug

Give the gift of life.  Register as an organ donor today!
http://www.organdonor.gov/beco <http://www.organdonor.gov/become.asp>mingdonor/

**Comment by Naatan** [comment]
Strange, I'm not seeing this. @mjainQA can you please test this?

**Comment by doughemi** [comment]
Problem resolved by downloading Komodo Edit (10.2.3). 

Komodo 9.3.2, which I was using, did not tell me that V 10 was available when I selected "Check for Updates" in the Help menu.

**Comment by qinwanguk** [comment]
I was going to report the same problem here.
It only suddenly happened few minutes ago. And i have been using it since the released date. 
As doughemi suggested, i am going to update to 10. but in case you still need some info to fix the bug.

build info:
Komodo Edit, version 9.3.2, build 16460, platform macosx(10.12.6)
Built on Thu Dec 10 19:37:46 2015.

memory 32G ddr3
CPU 3.5G xeon

**Comment by Naatan** [comment]
Thanks guys, the appropriate solution is definitely to use the latest version of Komodo.
