### ISSUE TITLE
Per-Language indentation is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2828]
### Short Summary

title.

### Steps to Reproduce

1. Set Ruby language settings to:
![image](https://user-images.githubusercontent.com/7100645/29244591-6fa30fba-7fc4-11e7-9e04-893a244c02ec.png)
2. Create a Ruby file (Places - Context Menu - New File).
3. Open it.
4. Press tab.

### Expected results

2 spaces.

### Actual results

4 spaces.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* -

### Additional Information

`require('ko/editor').scimoz().indent == 4` for the opened buffer.

**Comment by mitchell-as** [comment]
That's odd. It happens in 10.2 as well.

**Comment by mitchell-as** [comment]
Upon further investigation, there are two issues here:

1. While Komodo's global `prefs.xml` file (`src/prefs/prefs.p.xml`) has a `languages/Ruby/indentWidth` property set to 2, this value is not "found" in the "global" preference set when using Komodo. After manually changing the preference to something like 8, Komodo will save the "global" preference to the user's `prefs.xml` file, where it will be "found" and set correctly in Ruby files.
2. Attempting to change this preference back to 2 (from e.g. 8) will no longer work. The user's `prefs.xml` file will still reflect the old value (e.g. 8); it is not possible to set it to 2.

Re-assigning because I don't know what's going wrong with preferences.

**Comment by Defman21** [comment]
Is the fix applied in 90739?

**Comment by mitchell-as** [comment]
I don't know. Whenever the next nightly build comes out it will definitely be in that one.
