### ISSUE TITLE
"Create Komodo Language" does not properly generate a LangInfo class

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#286]
eg.

```
[2015-05-22 07:49:08,524] [ERROR] codeintel.langintel: error getting langinfo for 'Fuzzy' Traceback (most recent call last): File "/home/dooleyk/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/langintel.py", line 61, in langinfo self._langinfo_cache = self.mgr.lidb.langinfo_from_komodo_lang(self.lang) File "/home/dooleyk/Komodo-IDE-9/lib/mozilla/python/komodo/langinfo.py", line 311, in langinfo_from_komodo_lang raise LangInfoError("no info on %r komodo lang" % komodo_lang) LangInfoError: no info on u'Fuzzy' komodo lang
```

Reference: https://github.com/dooleyk/fuzzy

**Comment by polymeris** [comment]
Ran into this issue today. Is there a known workaround? How would one go about creating that class manually?

**Comment by mitchell-as** [comment]
Hi, in your "koFuzzy_UDL_Language.py" file, add this:

    from langinfo import LangInfo

    class FuzzyLangInfo(LangInfo):
        name = "Fuzzy"
        conforms_to_bases = ["Text"]
        exts = [".fzy"]

Komodo will automatically load your language's info on startup.

**Comment by mitchell-as** [comment]
Hmm, actually I misspoke. Komodo appears to only load LangInfo's on startup from its own LangInfo repository in "lib/mozilla/python/komodo/langinfo_*.py". You'll have to manually add your class to one of those files (pick one; it really doesn't matter).

**Comment by mitchell-as** [comment]
There is a bug in our handling of LangInfo's. Normally you'd be able to add a LangInfo to your extension, but Komodo is not reading it right now.

**Comment by mitchell-as** [comment]
It turns out there is no need to add a LangInfo if your language does not have any codeintel. If your language does have codeintel, the generated templates should provide it. No action is required on your part in the next release of Komodo. The notification should go away.

**Comment by dooleyk** [comment]
Mitchell, 

Thanks, I look forward to seeing it working in next release of Komodo, though I haven't noticed a fix in the nightly 9.2s so far. 

My agency bought 50 KomodIDE licenses to use with my custom language so they will be pleased. 

Kevin 
B-)x 

----- Original Message -----

**Comment by Naatan** [comment]
@dooleyk nice! May I ask what language that is?

Sounds like an interesting use-case. Be sure to let us know if you find any obvious ways that our language tools could improve your productivity in managing your custom language.

**Comment by dooleyk** [comment]
Hey Nathan, 

I've been supporting an in-house language we use to build web-based questionnaires at the U.S. Government Accountability Office (GAO) since 1999. We're similar to Canada's CAO if you follow that sort of stuff in Ottawa. 

We have been using HomeSite for many years to provide a development environment for our development software tools, which we call the Questionnaire Programming Language (QPL). But as you probably know, that hasn't been supported by Adobe for some time. Komodo is the only IDE (other than Eclipse which is much harder to build support for) that I've found that replicates integration features that HomeSite offered. 

I have developed a pretty extensive add on that uses both the language awareness features (mainly just the color-coding and code-completion so far) plus XUL-based code-writing wizards and compiling tools for Mac, Windows, and Linux. I've also added my own simplified Subversion support (which works with the svn command line tools in either Komodo Edit or KomodoID) because my users just write questionnaires and don't really understand what version control is about. 

You can see current development version at... 

https://respondemeum.com/komodo/ 

It will automatically update itself in Komodo when I push out a new release on this site (one of my most favorite features!). There is also a link on the page to some training videos that I've also prepared. 

If it installs ok, you can set your workstation preferences in the QPL extension add-on, and then build a new questionnaire project by clicking on the red "Q" in the QPL toolbar. It is basically a scripting language that lets you write your questionnaire in a simple language and then compile it to build about 100+ files in HTML, PHP, MySQL, and JavaScript to make it come to life on a real web server. 

The QPL toolbar has parallel Tools > QPL6 menu commands, as well as accessible key commands for personalization! 

My government web site is located at http://qpl.gao.gov, but that is not really updated for the new Komodo version yet. 

We're still making some infrastructure improvements in my server environment here but I'm hoping we'll be able to release this to my folks here in the next month or so with Komodo 8.5. 

You're help nudging improvements to 9.2 are very much appreciated! 

Kevin 
B-)x 





----- Original Message -----

**Comment by we3geeks** [comment]
@mitchell-as So what do we do with a language extension which does have code-intel and for which the language templates were created in a version of Komodo in which this bug exists/existed? It's not clear to me how I would resolve it, and that's precisely the situation I'm in...

**Comment by Naatan** [comment]
@dooleyk very interesting, you're giving me ideas just reading that. Thank you for sharing!

**Comment by mitchell-as** [comment]
@we3geeks Actually, 9.2.1 will resolve this for your case as well. (Right now it is still not clear to me how exactly LangInfo is used for extension languages. So far I'm not sure it is used at all.)

**Comment by polymeris** [comment]
Great. Looking forward to trying the nightly when it gets updated.

**Comment by we3geeks** [comment]
@mitchell-as I just updated to v9.2.1, and I'm still seeing the same repeated notification "ImportError: no module named cile_foo", so I think my question from Aug 6, above, still stands: how do we resolve this with a language extension whose skeleton was created with a v9.x version of Komodo which did not create the needed stub and which does have code-intel?

**Comment by mitchell-as** [comment]
@we3geeks You are describing a separate issue, which deals with code-intel specifically, not LangInfo. Please open a separate ticket for this.

**Comment by we3geeks** [comment]
@mitchell-as Thanks. I'll see if I can isolate this somehow and if I can, I'll create a new issue.

**Comment by we3geeks** [comment]
@mitchell-as See https://github.com/Komodo/KomodoEdit/issues/598
