### ISSUE TITLE
python codeintel goes 100 CPU

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2873]
### Short Summary
Suddenly codeintel CPU usage goes 100

### Steps to Reproduce
sorry no clue

### Platform Information

Komodo IDE, version 11.0.0-alpha1, build 90396, platform linux-x86_64.
Built on Thu Aug 10 00:23:22 2017.

### Additional Information

[codeintel3.log.txt](https://github.com/Komodo/KomodoEdit/files/1230533/codeintel3.log.txt)

**Comment by agroszer** [comment]
ohh after a while:

![screenshot_2017-08-17_10-05-45](https://user-images.githubusercontent.com/350912/29402019-acc80e5a-8333-11e7-8568-6c6529fa4236.png)

**Comment by Defman21** [comment]
I think Komodo should not start scanning until the user opens a project. Or at least if their wants to do that, it should be done manually.

**Comment by mitchell-as** [comment]
Komodo is not scanning at this stage. It is identifying candidate files to scan, and then prompts you to scan them (instead of automatically doing it, as in the past). It's a bit ironic, but probably necessary. @Naatan is the best person to address this.

**Comment by Defman21** [comment]
Thanks for the explanation!

**Comment by cgchoffman** [comment]
This is fixed in newer builds.  I'm assuming what happened here is you opened a file at the root of your project or home directory and so Code Intel started recursively looking for files to scan.  In this scenario Code Intel should only scan the current doc and relevant files in the current directory, non-recursively.

I hit this last week and @Naatan fixed it.  Thanks for reporting though @agroszer! Definitely would not want to release with this! @Naatan, if you think I'm right, I'll let you close.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/d0fb0a61cf39f01c20804d7ff5ab7e7146041164
