### ISSUE TITLE
Let's Get Started dialog issues

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3071]
The Let's Get Started dialog that pops up on first launch (prompting to configure Appearance and Integration) has an unfinished/broken look to it. There's an inert scrollbar on the sample code's text area that has no ends on it, and a bunch of whitespace in the text area after the code.

<img width="634" alt="screen shot 2017-09-14 at 10 15 51" src="https://user-images.githubusercontent.com/3590102/30444795-f915a8b0-9938-11e7-9296-532a5f9c9c17.png">

The dialog also remains above all other app windows, which is a little annoying.

Resizing the dialog vertically hides the Cancel/Back/Next buttons at the bottom.

Checking and then unchecking the Classic Mode checkbox leaves the Colour Scheme dropdown set to Classic, and the option that was previously selected can't be reselected until another option is selected first.

On the final page, "Hit Komodo > Preferences after this window closes in order to access all of Komodo Preferences" should perhaps say "...all of Komodo's Preferences" or "...all the Komodo Preferences".

On my initial run, though I checked the "Start the 'Getting Started' Tutorial when I finish this wizard" option, it did not seem to appear. On running the wizard again via the menu item, the tutorial did start afterward.

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

**Comment by Naatan** [comment]
> The dialog also remains above all other app windows, which is a little annoying.

This is unfortunately a limitation we cannot get around, because otherwise the window might open behind other windows.

Action items from this report:

 * Add border around scintilla preview so it's clear it is separate from the dialog background
 * Disable resizing 
 * Selection state isnt updated properly when toggling classic mode
 * Locale update for last page

I'm digging into the getting started tutorial not firing, that deserves a bug of its own.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/82df4f531a3f81324ab63de52be0e998a6a700c1
https://github.com/Komodo/KomodoIDE/commit/dfa724ca196a62ee2c66f9fa7c0b14b848a835cd
