### ISSUE TITLE
Code completion is not working for Perl Module functions

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#3117]
### Short Summary

Not getting code completion for some of the functions

### Steps to Reproduce
1. Create a new file Perl Module File (exp.pm)
2. Type the following and verify auto-completion option is available
```
use LWP;
$HTTP::Request::
```

### Expected results
See screenshot of 10.2.3 comparison with 11.0

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0, build 90667, platform macosx.
Built on Fri Sep 15 15:06:46 2017.
[pystderr_2017-09-18_13:24_Komodo IDE 11.0.0 (Build 90667).txt](https://github.com/Komodo/KomodoEdit/files/1312114/pystderr_2017-09-18_13.24_Komodo.IDE.11.0.0.Build.90667.txt)

### Additional Information
![image](https://user-images.githubusercontent.com/26605593/30562821-a1257196-9c74-11e7-9299-dfb6568c1f7b.png)

**Comment by mitchell-as** [comment]
Note to self: punting to 11.1. Perl's stdlib has a bunch of strange module imports. In the above example, the `LWP` module auto-imports `LWP::UserAgent`, which in turn imports `HTTP::Request` and friends. Thus, importing `LWP` should not only import completions for the `LWP` namespace, but should also create a `HTTP` namespace with completions. However, this scheme is contrary to CodeIntel's design to only resolve imports on demand. In the above case, `use LWP` should only import `LWP`, and `LWP::<|>` would resolve all imports in `LWP` on-demand and show completions then. Instead, it appears we'd have to resolve all of `LWP`'s imports immediately in order to fetch the `HTTP` namespace. Compounding this is the fact that `LWP::UserAgent` auto-imports `LWP` again, so recursion is an issue.

**Comment by ANSI-C** [comment]
Hello, I cannot get modules method completion as well, it is not working at all:

![image](https://user-images.githubusercontent.com/7015883/33372475-7815b12c-d4fe-11e7-9397-774100c15a8a.png)

I tested it with a module developed by be and located on a directory included in import directories list:

![image](https://user-images.githubusercontent.com/7015883/33372375-1a4d460e-d4fe-11e7-87d6-cfc04ebcd115.png)

it was working on v10

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/552f372b73cc05e3e413bff10c6bbc29820a4e25

**Comment by ANSI-C** [comment]
Hello, for me this still doesn't work on 11.0.2

**Comment by Defman21** [comment]
It's targeted for Komodo 11.1.

**Comment by ANSI-C** [comment]
Ok, thanks.
