### ISSUE TITLE
Komodo IDE loses all directories in explorer list when fails to connect to a remote SFTP one

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#3447]
Komodo IDE loses all directories in explorer list when fails to connect to a remote SFTP one

### Steps to Reproduce

set up some project directories, one sftp one among them, then shut down the sftp server

### Expected results

I should be able to switch to a local directory in drop down list on the left

### Actual results

the drop down list is void

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.2
*Operating System (and version)?* Windows 8.1

### Additional Information

![immagine](https://user-images.githubusercontent.com/7015883/35560518-f7e9405a-05ad-11e8-913f-3fc39e2184d2.png)

**Comment by babobski** [comment]
Looks to me that's this is the expected behaviour, when you set you're project to a remote location and the connection to the server is lost, you aren't able to choose a other directory on this location, because you lost the connection.

> I should be able to switch to a local directory in drop down list on the left

If you use the gear wheel on the right, you're still able to switch to a local directory or a other remote directory:

![afbeelding](https://user-images.githubusercontent.com/3530262/35623027-391114cc-068a-11e8-80c8-5d47ba1f24a2.png)

It doesn't make sense that you can switch here to a other location, you're viewing the directory of you're project, so choosing a directory that's not inside you're project is a bit weird. 

If you want to change the directory of you're project to a local one, you have to do this through the project settings menu.

I know you can switch to you're other project directories(local or remote) when you're have a connection to you're server, but when you switch using this dropdown, you're not switching projects only directories.
You can better use the projects panel to switch between you're projects(directories) as the correct project settings are loaded (codeintel settings, etc.).

**Comment by Naatan** [comment]
I agree with @babobski's assessment, this is the expected behaviour.

**Comment by ANSI-C** [comment]
Sirs, this is a clumsy "solution", a good program should never lose user's info/data. This is what is happening, and I call such behaviour a bug, not a "feature". I don't care anyway, this is a minor problem compared to autocompletion and code intel completely broken and not working.

**Comment by Naatan** [comment]
It didn't lose any data, you set the scope to a server connection which does not work. Effectively there is no data. You can still set your scope back to any local folder you wish, all your data is still there.

Komodo does not do offline caching of your remote connections, if this is something you're interested in I would recommend looking into Publishing instead.

http://docs.activestate.com/komodo/11/manual/publish.html

**Comment by ANSI-C** [comment]
Hello, tried to follow you advice, unfortunately the _Publishing_ feature is broken for what concerns symlinks.
It detects conflicts whenever syncing same directories with git detects none.

**Comment by ANSI-C** [comment]
As for _project_ feature is concerned, from what I can see there is no way to save _remote_ directories within a project.

**Comment by Naatan** [comment]
That is true, it does not support saving remote directories in a project.

At this stage the ticket here seems to have run its course though. Please open a thread on the forum if you'd like to further discuss use-cases.
