### ISSUE TITLE
Black popup dialogs.  OSX

### ISSUE THREAD

**Issue by NeilFraser** [Komodo/KomodoEdit#3475]
### Short Summary

Pop-up dialogs are solid black.

### Steps to Reproduce

Delete a file.

### Expected results

Confirmation dialog should appear.

### Actual results

Dialog is all black until the control buttons are moused-over.  Here's a video:
https://www.youtube.com/watch?v=ca2Wi6SR6T4

### Platform Information

Komodo IDE, version 11.0.2, build 90813, platform macosx. Built on Mon Dec 4 09:43:06 2017.

**Comment by cgchoffman** [comment]
I'm finding that sometime mouseover works and sometimes I have to click to get everything to appear.  I'm also noticing that the dialogs appear to have an off centre title which tells me they aren't sized properly (not that this should occur because of that).

Another note is that once I have had a dialog open broken, then mouse over or click to show the contents, that dialog never opens broken again.  @NeilFraser , have you noticed that?

**Comment by cgchoffman** [comment]
Possible workaround https://github.com/Komodo/KomodoEdit/issues/3508#issuecomment-373807755

**Comment by NeilFraser** [comment]
With native window borders **checked** I get a white dialog with a title:
![screen shot 2018-03-16 at 12 04 42](https://user-images.githubusercontent.com/250480/37539892-4fd52a86-2912-11e8-8357-2d50d2c19153.png)
Mouseing over the control buttons (top-left) does nothing, but mousing over the command buttons (bottom-middle) rerenders the dialog properly.

With native window borders **unchecked** I get the black dialog in the video with no title where both the control and the command buttons rerender the dialog properly.

I have not noticed the off-centre title you mentioned.

**Comment by itcjohn** [comment]
At the moment I'm facing the problem with macOS High Sierra. Are there any improvements, tricks, workarounds?

**Comment by Naatan** [comment]
I've found disabling GPU acceleration in Komodo solves the issue for me:

http://docs.activestate.com/komodo/11/manual/trouble.html#artifacts

**Comment by itcjohn** [comment]
Works for me. Nice. Thank you.
