### ISSUE TITLE
Current line background color overrides any other background colors in current line

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#356]
![pic 1](http://i.imgur.com/Egjp38t.png)
![pic 2](http://i.imgur.com/bYBOolZ.png)

**Comment by mitchell-as** [comment]
Hi, this is by design. Indicators like the one you have shown are drawn in the background (via `indicSetUnder(true)`), so-as not to interfere with more important, foreground indicators (lint, underlines, etc.). Background indicators happen to be drawn under the caret background line by the editing component we use (Scintilla).

You'd have to call `indicSetUnder(false)` in order to have a particular indicator display on top of the background line.

**Comment by Defman21** [comment]
Ahh, thanks Mitchell! So I just have to call `indicSetUnder(false)` in a macro for example?

**Comment by mitchell-as** [comment]
You'd have to know the indicator's number first, and then use it in `indicSetUnder()`. For example, if the indicator's number was 27 (which is the indicator for found text in a search), then you'd call `indicSetUnder(27, false)`.

**Comment by Defman21** [comment]
Where I can find the whole list of indicators number? Can I get them all in list/array by a function? (Python or JavaScript, no matter what to use)

**Comment by mitchell-as** [comment]
https://github.com/Komodo/KomodoEdit/blob/master/src/lint/koILinter.idl

They're numbered starting on the line "const long DECORATOR_ERROR = 15;"

**Comment by Defman21** [comment]
Thanks!

**Comment by Naatan** [comment]
Let me know how that works out Defman (ie. you'll likely be running into other issues now, where your indicator is overlapping other useful information).

**Comment by Defman21** [comment]
It works fine to me. I don't see any bugs/issues with that.
![scr](http://i.imgur.com/iK26pRK.png)
If I find any issues - I post it in this issue.
