### ISSUE TITLE
Code Intel failure (tcl)

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#399]
AttributeError: 'TclLangIntel' object has no attribute 'async_eval_at_trg'
                           Fri Jul 03 2015 15:31:13 GMT+0100 (GMT Standard Time)

I was going to attach the file that gives rise to this error but can't see how to do it. What was wrong with your old bug system?

**Comment by Naatan** [comment]
It was too convoluted and unfriendly to new users. Github issues is not ideal either, but no bug tracker is, and github opens us up to a much wider audience.

Are you actually seeing an issue related to this or are you just sharing an error you saw in your log?

You can share files just by pasting them in here (textual) and wrapping them in code tags (see markdown documentation), or use [github gist](https://gist.github.com/).

**Comment by sgeard** [comment]
The error was as reported by Komodo in the log window. After I posted it there was an update and now it's fixed so this issue can be closed.

How do I do that in the new world or is that what 'Close and comment' does? Perhaps the previous system was difficult for new users but at least the bug's progress was clear. It is not at all obvious to me that this is a proper bug-tracking system, its more like a formatted list with labels. Still, I'm always willing to try something new so I'll try it a few times before passing judgement! What is a 'pull-request'?

**Comment by sgeard** [comment]
The title at the top is Komodo / KomodoEdit but I was directed here by the 'Report a bug' menu entry in KomodoIDE. Is this still the correct place?

**Comment by Defman21** [comment]
Pull request is a... pull request. If you did some changes in a forked repo (you can also call it "a clone" or something like that) and you want to see your changes in the main repo (for example you increased Komodo speed by making a lot of optimization or just fixed some few things in the code) - you have to create a pull request. Until you're just a bug reporter, it's not something you should know on the level we (I and Komodo devs and a lot of another devs that uses Github) know. The Issues of this repo is the correct place for both versions of Komodo - IDE or Edit. If the issue affects only IDE version - it will be marked as IDE only issue (https://github.com/Komodo/KomodoEdit/labels/IDE%20Only)
You can close your issue without providing any comment. Just press `Close Issue` button.
![screen](http://i.imgur.com/Q9pAqUT.png)
Hope I wasn't THAT boring :smiley: And I hope you understand me perfectly, because English is not my native language and I'm still learning it.

**Comment by Naatan** [comment]
Close issue is fine :) The old system was much more convoluted, on the new system the most obvious answer is usually the right answer.

**Comment by sgeard** [comment]
Thanks, your explanations were very clear.
