### ISSUE TITLE
TCL syntax checker fails for umlauts

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#401]
The following TCL code snipped shows an "wrong # args" in "set Workspace L".
The issue is the umlaut above it.
The file must be saved as ASCII, not as utf-8 (which is (unfortunately) the tcl default)
```
console show
switch -exact -- L {
	D {
		set Ret [list 4 "Schritt nicht hier (abfüllen)"]
	}
	L { 
		set Workplace L
	}
}
```
I don't know how to add files. The "verbatim" removes the tabs so this might not work without tabs.

This ticket system is really a step backward, sorry folks...

**Comment by Naatan** [comment]
> This ticket system is really a step backward, sorry folks...

Everyone has their opinion, many like github issues much better. Personally, being someone who uses it far beyond just reporting bugs, I find it a LOT better.

Back to the topic at hand. Far as I can tell "ü" is not a valid ASCII character. So the issue here is simlpy that you are using ASCII but using non-ASCII characters.

**Comment by oehhar** [comment]
Sorry, it is a valid TCL script. I am sorry to use the word "ASCII encodation", but that is what is written in the corner right down. In reallity, it is cp1252.

If you decide not to chase this bug, it is your choice.

Thank you,
Harald
