### ISSUE TITLE
SDK API for Component Interfaces and Classes

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#419]
I want to see something like 
```js
var RCS = require("ko/services")("koIRemoteConnectionService");
// ie. Cc["@activestate.com/koRemoteConnectionService;1"].getService(Ci.koIRemoteConnectionService);
```

**Comment by cgchoffman** [comment]
I don't agree with that syntax.  Why that particular structure @Defman21 ?

**Comment by Defman21** [comment]
It's just an example. You can change this syntax if you don't like that. Let's discuss! How this should looks in your opinion? Maybe
 ```js
require("ko/components")("@activestate.com/Component" /* Component */, 1 /* Version */).service("koIRemoteConnectionService")
```

**Comment by Naatan** [comment]
The SDK is meant to abstract these types of API's, not alias them.

That said, one could easily make an alias module. Eg.

```
require("aliases").remoteConnections // aliases to Cc["@activestate.com/koRemoteConnectionService;1"].getService(Ci.koIRemoteConnectionService);
```

That would have to be a manual process though, otherwise you're alias is pretty redundant.

Not something we'd be supporting natively, we're trying to move away from these very low level API's in our SDK's, not facilitate them.
