### ISSUE TITLE
CodeIntel OOP protocol byte length count is not ideal

### ISSUE THREAD

**Issue by cweagans** [Komodo/KomodoEdit#435]
I'm referencing https://github.com/Komodo/KomodoEdit/wiki/290-CodeIntel-OOP-Protocol

If I have a string of JSON, say: `{"command":"whatever"}`, which is 22 characters long, you'd expect to be able to send `21{"command":"whatever"}` to codeintel and have it work, right? *Wrong!*. The correct string to send is actually `23{"command":"whatever"}` because the two numbers at the beginning add two more bytes to the string.

This is very dumb, and is difficult to develop against, especially when you have JSON strings that are 9, 98, 99, 997, 998, 999 characters long. Granted, this doesn't happen that often and there are only 6 cases that my code is likely to run into, but there's a known solution to this problem, and it's not difficult to do.

There are a couple of solutions to this problem:

1. Don't include the byte count in the total byte count. I'm not sure why it was like this in the first place, but it just seems wrong. Look for numbers until you hit the first `{` character of the JSON and parse things out from there.
2. Just use Netstring, which is a standard way of sending a specific number of bytes over the wire.
3. Don't use a byte count at all. This one makes the most sense to me, and you can do it in a backward compatible way. You have a well structured piece of data that you're expecting (JSON with appropriately balanced quotes and brackets), and you should know when you receive it all. If there's a byte count as required now, then use it (or just ignore it and strip it out of the received data). If not, then rely on getting well-structured JSON.

**Comment by Naatan** [comment]
I get that it is missleading, but I don't follow your reasoning of "hard to develop against"? You could easily use a small helper function that parses these calls for you.

I agree that this could probably be improved (I say probably because I dont know why it was done this way, and one must assume there was probably a good reason for it), I'm simply questioning the severity.

@Mook-as since you probably developed this, or dealt with it, can you comment?

**Comment by cweagans** [comment]
I guess "hard" isn't the right word. "Weird" is probably more accurate, and yeah, the severity is pretty low. I mean, it works...I just don't know why it should work like *that*, especially when there's a standard way of handling this in the rest of the software world.

**Comment by Mook-as** [comment]
Hmm. I no longer recall why that was done that way; and I agree, that's dumb.  Standard representation or not, something else can be subbed in.

(I didn't want to just do brace scanning / JSON parsing because it can get ugly if the payload contains strings with unmatched braces; but for length-prefixed strings there's no reason to keep the prefix length in there.  I also didn't trust other languages to have JSON parsers that would correctly eat only the bytes it need and leave the next message alone.)

**Comment by mitchell-as** [comment]
I'm going to mark this as "by design" as I see no flaw and there has been no discussion for a while. If the discussion resumes, I can re-open.
