### ISSUE TITLE
Packages: Hide incompatible packages (9.2+)

### ISSUE THREAD

**Issue by nblackburn** [Komodo/KomodoEdit#454]
![Packages](http://images.contentful.com/bj1g69m2935w/53s8lAeTZuuqqc46meOguA/19c882ec68f1901a166368c415c74851/packageinstaller.png)

http://komodoide.com/blog/komodo-9-2-pre-release-ready-for-testing

Within the new Packages feature, all packages are shown regardless of compatibility. I feel it would make sense contextually to hide ones that are not supported by the running version of Komodo.

**Comment by Defman21** [comment]
99% of packages are compatible, IIRC checking for compatibility process was dropped.

**Comment by Naatan** [comment]
Yes, checking for compatibility is dropped, it will warn you if a package might not work with your version of Komodo. Note the first nightly we released did not have this compatibility check disabled yet, so you may have to update your nightly.

**Comment by nblackburn** [comment]
I meant within the new "Packages" feature which just seems to show everything and warns you afterwards.

**Comment by Naatan** [comment]
The problem with that is that we would depend on package authors to update their version numbers each time we update ours. Its not because an author did not update their version requirements that it doesnt work with the latest version of Komodo, in fact in 98% of cases it works just fine.

So rather than hide ALL packages that do not have their version update we simply warn you that there MIGHT be some issues with this package, which again, is not very likely.
