### ISSUE TITLE
Default Komodo Get Add-ons

### ISSUE THREAD

**Issue by pacav69** [Komodo/KomodoEdit#472]
Default Komodo Get Add-ons points to v8 these don’t work on v9.*
![komodoaddons](https://cloud.githubusercontent.com/assets/2259579/9020461/0cd6bbde-3840-11e5-9192-76ac913a5555.png)

**Comment by Naatan** [comment]
Thanks @pacav69, note this addon screen is being deprecated and will be gone entirely in Komodo 9.3. You can use the Package installer (accessible under Commando / Go to Anything) as of Komodo 9.2, which is currently available as a pre-release.

That said, given that this is being deprecated and you are the first that reported this since the release of Komodo 9, I don't see this being worth fixing.

**Comment by pacav69** [comment]
Just thought i would point it out just in case it was overlooked.
