### ISSUE TITLE
Support setting using other terminals

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#547]
Atm we only support running commands in xterm it seems.

**Comment by Naatan** [comment]
Workaround: You could create your own xterm "script" which launches whatever terminal you prefer. Just make sure it's on the PATH in the Komodo environment settings.

**Comment by ervumlens** [comment]
This reminds me of #250, with "Show in File Manager" functionality tied to Nautilus and Konqueror. Same deal, it's possible to create a "shim script" to use something else. 

@naatan Think the two issues are worth addressing together? (I don't have a dog in the fight since I use a "nautilus" workaround script.)

**Comment by th3coop** [comment]
I think this commit must resolve this ticket: https://github.com/Komodo/Komodoide/commit/b41deef16
