### ISSUE TITLE
Add Icons for Existing Remote * ... back to front and inconsistent

### ISSUE THREAD

**Issue by mafoo** [Komodo/KomodoEdit#572]
When right clicking a open project to Add Something the Icons for Existing Remote File... and Existing Remote Folder... are back to front and the other icons are inconsistent to the theme
![komodobug](https://cloud.githubusercontent.com/assets/2932039/9655742/35fc2f6c-522b-11e5-80cd-a43f4040cd05.png)
For reference i am on the Classic iconset

**Comment by Naatan** [comment]
Unfortunately inconsistencies like this will happen in places. The classic iconset isn't going to give you 100% coverage. 

I'll have to close this issue for now since the classic iconset will be moving into it's own Komodo Package, once that's done it'll be very easy for community members to supply fixes/enhancements to it.
