### ISSUE TITLE
"Add-on compatibility checking is disabled" message keeps coming back

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#591]
After updating to v9.2.1, whenever I open the "Add-ons Manager" window, it always shows the following message: "Add-on compatibility checking is disabled. You may have incompatible add-ons.", followed by an "Enable" link. Nothing is listed as in incompatible add-on if I scroll down through the full set of add-ons. Clicking the "Enable" link makes the message go away, but it comes back if I restart Komodo.

![komodo-20150909a](https://cloud.githubusercontent.com/assets/2390335/9779544/dcfa2f40-5739-11e5-97b1-8ea5066873df.png)

It seems like there's something amiss with the warning message, or it isn't actually showing me the incompatible add-ons, or the "enable" setting isn't sticking, or some combination of those.

Build info: 
Komodo Edit, version 9.2.1, build 15998, platform macosx.
Built on Wed Sep 2 00:18:38 2015.

Same behavior in Komodo IDE; build info:
Komodo IDE, version 9.2.1, build 87651, platform macosx.
Built on Tue Sep 1 18:03:46 2015.

**Comment by mitchell-as** [comment]
With the new package management features landing in Komodo 9.2, we chose to disable add-on compatibility checking completely. This is because users are forewarned that a package may be incompatible, but they are given the option to install anyway. In that event, we need to have compatibility checking disabled. Eventually we will do away with the add-ons manager so you will not have to see this oddity.
