### ISSUE TITLE
don't block typing with autocomplete select box

### ISSUE THREAD

**Issue by arnoldbird** [Komodo/KomodoEdit#608]
With autocomplete turned on, a select box appears in the same location where text is being typed, blocking the text that's being typed.  This is distracting, and provides no advantage vs opening the select box somewhere else in the UI.

**Comment by mitchell-as** [comment]
Hi, my guess is that you are using a non-standard DPI that affects the correct placement of autocomplete boxes, as the boxes are always supposed to be below the current line. I'm going to close this issue since we're tracking this in https://github.com/Komodo/KomodoEdit/issues/162.

References:
1. https://github.com/Komodo/KomodoEdit/issues/162#issuecomment-129976281
2. http://forum.komodoide.com/t/komodo-scrolls-up-on-autocomplete/2025
