### ISSUE TITLE
Remote debugging Perl scripts always break in DbgrCommon.pm

### ISSUE THREAD

**Issue by ziermmar** [Komodo/KomodoEdit#644]
When invoking the debugger, it always breaks on DbgrCommon.pm, line 391.
DbgrCommon.pm part of the server portion of Activestate's remote debugging libraries for perl. 

See also http://forum.komodoide.com/t/remote-perl-debug-always-breaks-in-dbgrcommon-pm/2073/7 for more details.

**Comment by ziermmar** [comment]
I'm running Archlinux, Perl 5.22, Gnome 3.18. Remote Server: Apache 2.2 / Perl 5.10. I've setup another apache 2.4 on my dev machine locally, still resulting in the same behavior...

Link to screencast: https://www.fullmotion.de/files/komodo-debug/

**Comment by palmerj** [comment]
Any further progress on this? This is really annoying. I'm running Komodo 10.0 on MacOSX

**Comment by mitchell-as** [comment]
No, there hasn't been progress on this, sorry :(

**Comment by djstauffer** [comment]
I ran into this problem today, after upgrading from using the 9.1.0 version of the KomodoPerlRemoteDebugging package to version 9.3.2

I am running on debian jessie (64 bit).  I confirmed this on two machines.  The 9.1.0 version of the remote debugging package does not have this problem.  I am running against Komodo IDE 9.3.2.

This problem occurs on the simplest of programs:

  #!/usr/bin/perl

  print "hello\n";

If (from a bash prompt) you run:

export PERL5LIB="{dir-where-extracted}/Komodo-PerlRemoteDebugging-9.3.2-88191-linux-x86_64"

then 

export PERLDB_OPTS="RemotePort=127.0.0.1:9000"

... and then run the above program (e.g. I save it as test.pl, and run "perl -d test.pl"), Komodo will allow you to step over that single line, then it will jump into the xmlHeader() sub in DbgrCommon.pm.  If you then try to step over the first line in the xmlHeader() sub, you get the message "Debugger is starting..." at the bottom center of the Komodo IDE window, and the debugging session stops responding.

Again, this does not happen with the 9.1.0 version of the remote debugging package (when used with Komodo IDE 9.3.2).

I ran a diff between the two versions of the remote debugging package, and the only thing that has changed is the perl5db.pl file.  And not a lot has changed their either.  Here is the diff:

`diff Komodo-PerlRemoteDebugging-9.1.0-87337-linux-x86_64/perl5db.pl Komodo-PerlRemoteDebugging-9.3.2-88191-linux-x86_64/perl5db.pl 
2296c2296
<     if ($ldebug && $pkg !~ /^DB::/) {
---
>     if ($ldebug && ($pkg !~ /^DB::/ || $filename !~ /dbgp[\/\\]perllib/)) {
2358c2358
<     if ($pkg !~ /^DB::/) {
---
>     if ($pkg !~ /^DB::/ || $filename !~ /dbgp[\/\\]perllib/) {
2377c2377
<     if (!$single && ($trace & 2) && $pkg !~ /^DB::/) {
---
>     if (!$single && ($trace & 2) && ($pkg !~ /^DB::/ || $filename !~ /dbgp[\/\\]perllib/)) {
2398c2398
< 	&& ($pkg eq 'DB::fake' || $pkg !~ /^DB::/)
---
> 	&& ($pkg eq 'DB::fake' || $pkg !~ /^DB::/ || $filename !~ /dbgp[\/\\]perllib/)
4262c4262
<     } elsif ($pkg =~ /^DB::/) {
---
>     } elsif ($pkg =~ /^DB::/ && $filename =~ /dbgp[\/\\]perllib/) {
4384c4384
<     my $inDB = ($pkg && index($pkg, "DB::") == 0);
---
>     my $inDB = ($pkg && index($pkg, "DB::") == 0 && $filename =~ /dbgp[\/\\]perllib/);
4643c4643
< 	if ($sub =~ /^DB::/) {
---
> 	if ($sub =~ /^DB::/ && $file =~ /dbgp[\/\\]perllib/) {
`

I suspect those tests on the filename are somehow to blame, since those are the only changes, and the code works for me when they are not there.  Perhaps there is someone at ActiveState that can use this to find the bug.  Surely you have someone there who understands how this all works.

Hope this helps.  I'd really like the bug to be fixed.

**Comment by mitchell-as** [comment]
Thanks for the ping. Please see https://github.com/Komodo/KomodoEdit/issues/309#issuecomment-236215939. The solution is to change the directory structure of your remote Perl debugging bits to match "dbgp/perllib", despite the directory structure of the download. There is an open ticket to update our documentation in (https://github.com/Komodo/KomodoEdit/issues/1870). Sorry for the inconvenience.

**Comment by djstauffer** [comment]
Hey no problem.  Glad there was such an easy way to fix it.  I'm kind of surprised I didn't find issue #309 in my search, but that's how it goes sometimes.

One other problem I had (which is actually what brought this whole thing up)...  If I try to debug the same script in taint mode ( with or without warnings, "perl -wTd test.pl" or "perl -Td test.pl" ), Komodo shows that there is a debugging connection to port 9000 (under Listener Status), but it never shows the source code or anything else, it just sits there.  I've searched to find a fix for this also, but have come up empty-handed.  Any suggestions on that would be appreciated.

**Comment by djstauffer** [comment]
Ah, I just found it -- when you use taint mode, the PERL5LIB environment variable is ignored, so the debugging libraries aren't found.  When I ran "perl -wTD -I{dir-where-extracted}/dbgp/perllib/Komodo-PerlRemoteDebugging-9.3.2-88191-linux-x86_64 test.pl it worked just fine.

Hopefully this comment will help someone else who might have that problem.
