### ISSUE TITLE
9.3 code intelligence

### ISSUE THREAD

**Issue by Piniol** [Komodo/KomodoEdit#673]
Code intelligence window is black and without scrollbar. Also word matching is not accurate. Details in attachet image. Same for PHP. (Windows 8.1 x64)
![komodo1](https://cloud.githubusercontent.com/assets/15010011/10330945/a9fb7fa6-6cd1-11e5-9104-e0ce1e1b463b.jpg)

**Comment by Naatan** [comment]
You appear to have Prefs > Appearances > "Color HUD with Color Scheme" unchecked, that'll color HUD elements like autocompletions dark like that.

Please file a separate bug for your "word matching" issue and describe exactly what the problem is. I can't tell from what you said what you were expecting to happen that didn't happen.
