### ISSUE TITLE
Scrollbar Flickering on Snippet Properties

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#71]
Only happens with native scrollbars (dont use skinned scrollbars)

**Comment by toddw-as** [comment]
Which platform? I haven't seen this in Mac OS X (either dev build, nor release build) when using native scrollbars.

How often is it flickering?

**Comment by Naatan** [comment]
Make sure you have "Show scrollbars when scrolling" set in OSX.

It hides/shows as fast as it would if you would start/stop scrolling when that above setting is set.

**Comment by toddw-as** [comment]
Checking the code, this is the only thing that might have some affect on this, otherwise it's probably coming from the plugin hiding/showing itself (a trick used to ensure the plugin becomes visible):
  https://github.com/Komodo/KomodoIDE/commit/76ef02b (master)
  https://github.com/Komodo/KomodoEdit/commit/d09f738 (master)
