### ISSUE TITLE
Make codeintel work with all string lengths

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#880]
At the moment codeintel triggers at X characters (X is hard coded per language), any more or less and it won't trigger. If you are above the X characters then the autocompletion dialog will just narrow down on its existing results.

We want to make this work on all lengths, or at least lengths above X. The main reason this functionality is currently hard coded to one length is performance, but it's been many years since this was implemented and codeintel is now out of process. However performance is something to keep in mind when working on this, we do not want there to be any noticeable lag for the end-user.

Fixing this will also fix a big annoyance I've had for years, which is that altering a word almost never triggers completions as you need to be typing the xth character to make those work.

**Comment by mitchell-as** [comment]
From #871:



After investigating, codeintel has been operating under the assumption that it is always called immediately after each keypress. Therefore it cannot handle the new timeout mechanism.

The timeout mechanism has been reverted in 9.3.x.

For Komodo 10, work will need to be done to have codeintel work with any text behind the caret, not hard-coded positions based on the assumption of having the current state (which was the case pre-timeout). This affects at least Javascript, Python, and Ruby. All languages are likely affected. Unit tests will also need to be written to account for the new functionality. For example:

Javascript: setT will need to complete setTimeout.
Python: __a will need to complete __abs__ and __add__.

**Comment by mitchell-as** [comment]
Upon further investigation, this task is no small undertaking and will require a significant overhaul of codeintel as we know it. Codeintel was introduced over a decade ago (in Komodo 3) as an in-process feature. As such, it could (and would) frequently block the UI while indexing code or determining completions. In order to keep these distractions to a minimum Codeintel's architecture was built around a set of constraints. Among these constraints that are applicable to this ticket are:

1. A hard-coded symbol length of 3. Komodo will only auto-popup completions for (top-level) symbols starting at length 3. As an in-process feature, Komodo would listen for keypresses and trigger codeintel as needed. Since calculating completions can be an expensive process (especially for top-level symbols like globals), Codeintel's authors seemed to decide a length of 3 was a reasonable trade-off in terms of computation and user experience (just long enough to keep the user from having to type too much, while not popping up too often with short symbol names).
2. A global symbol database keyed with length-3 symbol names. In languages like PHP and JavaScript where global variables and functions are prevalent and numerous, quick symbol lookups for completing globals is essential. Since a symbol length of 3 was agreed upon in (1) above, it made sense to generate a quick lookup database with keys of length 3.
3. All unit tests were grounded in length 3 symbols. Self explanatory.

Now, it was not until Komodo 5 I think that Codeintel was moved to an external process, so the foundations of this architecture (like (1) and (2) above) had already sunk in and were likely difficult to change.

Based on all of the above, changing a fundamental assumption of Codeintel's, that autocompletions are triggered on (top-level) symbols of length 3, would almost seem like a restructuring of Codeintel itself. It's not quite that drastic, but it is certainly no small matter. There's also the fact that Codeintel's unit tests are structured around this length of 3. Many tests may need to be changed, updated, or created in order to support a variable length of characters.

Therefore this ticket must be tabled until at least Komodo 11. Introducing this into 10.x would be far too risky.

**Comment by Naatan** [comment]
Couldn't we simply do a codeintel lookup for the first 3 characters and let XUL autocompletions take it from there? ie. we can trigger it on the 5th char but still do the lookup on the third.

**Comment by mitchell-as** [comment]
Note: despite the milestone, this will not land in Komodo 11 due to the fact that our parsers are not scheduled to change. The hard-coded limits will remain until we rework our parsers.

**Comment by mitchell-as** [comment]
It turns out we had time to rework some bits of the parsers so this has been added and will appear in Komodo 11.
