### ISSUE TITLE
Project Load -> Toolkit Exception

### ISSUE THREAD

**Issue by octlabs** [Komodo/KomodoEdit#943]
Alter popup every launch after update to 9.3

<img width="640" alt="scrennshot 2015-12-10" src="https://cloud.githubusercontent.com/assets/8456418/11718025/2353cbc4-9f54-11e5-9d7a-33cada71d130.png">

Komodo IDE, version 9.3.1, build 88153, platform macosx.
Built on Tue Nov 17 11:36:24 2015.

**Comment by Naatan** [comment]
This is due to a third party addon, which appears to have been abandoned (no longer maintained): https://github.com/StanAngeloff/komodo-html-toolkit

I would recommend you uninstall it, these addons may be good replacements: 

 * http://komodoide.com/packages/addons/html-tools/
 * http://komodoide.com/packages/addons/html-entities-pane/
