### ISSUE TITLE
Drag and Drop in editor, add preference to turn it off

### ISSUE THREAD

**Issue by dwsongbird** [Komodo/KomodoEdit#954]
When using the Komodo Editor, instead of a mouseclick and movement selecting text, it "sometimes" drags and drops the text. This is an annoyance, it would be helpful to turn it off.

**Comment by cgchoffman** [comment]
This usually means that you've already got text selected and is expected behavior.  We could try adding a preference to disable dragging and dropping text but I don't think many people would actually want that.

**Comment by dwsongbird** [comment]
Hi Carey

I'm impressed how fast you respond!

However, this person does want to turn it off.
And if we're talking about what we "think" most people want then I "think" most people don't want that behaviour and at least want to turn it off.
However, you may have conducted a survey about this?

Obviously it's up to you, but the more "nervous" the UI the less attractive the tool.
And it's a pain when the code is suddenly moved by some unexpected mouse mode.

David






On 14 Dec 2015, at 19:19, Carey Hoffman <notifications@github.com> wrote:

This usually means that you've already got text selected and is expected behavior. We could try adding a preference to disable dragging and dropping text but I don't think many people would actually want that.

**Comment by Naatan** [comment]
We have not done research on this particular issue, but we all use Komodo day in day out and have never experienced this issue, nor have we seen any substantial number of reports from people having this issue. So it seems that the issue you are experiencing is relatively unique to a certain workflow, perhaps the mouse you are using, or some OS level setting.. hard to say.

Could you explain step by step how you reproduce the issue? Provide as many detail as possible.

**Comment by dwsongbird** [comment]
Hi Nathan

Thanks for treating my request seriously.

It's easy to reproduce (Mac OSX 10.11.1).
In the Komodo editor (I'm working on JavaScript files, if that matters) select some text with the mouse, i.e. click and drag to highlight, release the mouse.
Now click inside the selected area. The selected area is dragged and dropped.

I'd like a preference to turn off this modal behaviour, and always have selection with the mouse and never have drag and drop to move the selected text area, since I can do that better with cut and paste via the keyboard.
Perhaps it's because I prefer to use the keyboard where possible, and only use the mouse to quickly select things I want to copy. Anyway, I'd like to switch the drag and drop off.

Hope this makes the cut

David









On 14 Dec 2015, at 21:24, Nathan Rijksen <notifications@github.com> wrote:

We have not done research on this particular issue, but we all use Komodo day in day out and have never experienced this issue, nor have we seen any substantial number of reports from people having this issue. So it seems that the issue you are experiencing is relatively unique to a certain workflow, perhaps the mouse you are using, or some OS level setting.. hard to say.

Could you explain step by step how you reproduce the issue? Provide as many detail as possible.

**Comment by Naatan** [comment]
Hi David,

If what you are saying is correct then an option to disable mouse dragging would only be a workaround, as it sounds like a bug to me. So rather than providing a workaround for a bug, let's try and solve the bug.

First though I just want to make sure I understand you correctly, can you confirm that this reproduces the bug:

 * Place caret at start of string, press left mouse button down
 * Drag caret to end of the string, release left mouse button
 * Click (mouse down, mouse up, with very little delay) on the selection

These steps would cause the selected text to somehow be transformed for you? For me this just clears my selection.

If those steps are indeed correct, can you please supply the following information:

 * A before and after snippet, demonstrating how your text is altered and including an explanation of what you had selected and where you have clicked
 * If possible, a screencast of you reproducing the issue
 * A list of installed software that relates to handling any sort of input events
 * The brand and model of your mouse 

I realize that is quite a bit of information, but as we cannot reproduce the issue we need as much info as possible to find out what's going on.

Thank you

**Comment by dwsongbird** [comment]
Hi Nathan


As I said in my last mail
"select some text with the mouse, i.e. click and drag to highlight, release the mouse.
Now click inside the selected area. The selected area is dragged and dropped."
Perhaps I should have written: "Now click inside the selected area and hold the mouse button down. The selected area is dragged and dropped."

If I do what you suggest with the caret (rather than just the mouse pointer, leaving the caret wherever it happens to be) I get exactly the same behaviour as described above, i.e. the caret seems to be irrelevant.
In both cases the second click picks up the selected area and any movement of the mouse drags the area. Obviously if I release the mouse ("mouse up" in your description) then the area is dropped, and if the mouse hasn't moved since the selection, then the text stays where it was. And, as you say below, the selection is gone.
But if the mouse does move while the button is pressed, then we're into drag and drop mode, and the text is moved.

As Carey Hoffman wrote yesterday "This usually means that you've already got text selected and is expected behavior. ". But I'd like to turn it off, please.

Yours

David






On 15 Dec 2015, at 17:42, Nathan Rijksen <notifications@github.com> wrote:

Hi David,

If what you are saying is correct then an option to disable mouse dragging would only be a workaround, as it sounds like a bug to me. So rather than providing a workaround for a bug, let's try and solve the bug.

First though I just want to make sure I understand you correctly, can you confirm that this reproduces the bug:

Place caret at start of string, press left mouse button down
Drag caret to end of the string, release left mouse button
Click (mouse down, mouse up, with very little delay) on the selection
These steps would cause the selected text to somehow be transformed for you? For me this just clears my selection.

If those steps are indeed correct, can you please supply the following information:

A before and after snippet, demonstrating how your text is altered and including an explanation of what you had selected and where you have clicked
If possible, a screencast of you reproducing the issue
A list of installed software that relates to handling any sort of input events
The brand and model of your mouse
I realize that is quite a bit of information, but as we cannot reproduce the issue we need as much info as possible to find out what's going on.

Thank you

**Comment by Naatan** [comment]
>  "Now click inside the selected area and hold the mouse button down.

So you are actually holding the mouse button while having a selection? That seems to be the proper user experience then. What would you expect to happen? Or put differently, why are you holding your mouse button?

**Comment by dwsongbird** [comment]
Hello Nathan

What I want to happen, is that a new selection starts, NOT a drag and drop.
And to put it the other way: I'm holding the button to start selecting, not to start dragging.

I feel we're going round in circles here, two days ago cghoffman wrote "This usually means that you've already got text selected and is expected behavior. We could try adding a preference to disable dragging and dropping text".







On 15 Dec 2015, at 21:49, Nathan Rijksen <notifications@github.com> wrote:

"Now click inside the selected area and hold the mouse button down.

So you are actually holding the mouse button while having a selection? That seems to be the proper user experience then. What would you expect to happen? Or put differently, why are you holding your mouse button?

**Comment by Naatan** [comment]
Like I said that would be adding a workaround for a bug. We want to squash the bug rather than work around it, if indeed there is a bug.

I've asked some very concise questions in comment https://github.com/Komodo/KomodoEdit/issues/954#issuecomment-164822103, would you please be willing to answer them as far as possible? That will help us narrow down the issue. If my steps are incorrect please explain your steps in the same concise way. With your current explanation there is too much grey area where you expect us to fill in the blanks, which we can but that would defeat the purpose of providing reproduction steps.

**Comment by cgchoffman** [comment]
I'm not getting a bug out of this @Naatan .  @dwsongbird selects some text.  Immediately they click and drag in the selected text to select a different portion of that text.  The result is that the currently selected text gets dragged.  We can look into a pref but I suspect that this would need to override scintilla event handling which I'm guessing @mitchell-as, rightly so, will say is a bad idea.

**Comment by mitchell-as** [comment]
@cgchoffman is right, this is not a bug, but the functionality in the Scintilla editing component. Clicking with a selection initiates drag and drop, not a "reselect" type of behavior. We'd probably end up patching Scintilla to optionally turn on/off DnD.

**Comment by Naatan** [comment]
Thanks @mitchell-as, I think that is probably what I was missing, the "expected" result. I had not considered a reselection being what someone would want in that case. @dwsongbird does that sound right?

This dragging behaviour is pretty much default all across the board, your browser,  word, google docs, other programming editors, they all act the same way. While I understand you would like this behaviour the truth is that you are likely a minority, if not simply the only one, that wants this behaviour. Since this would take us patching our editor component (which is significant) I just don't see it being a smart investment on our end. I am sorry. If more people indicate that they would like this behaviour I will reopen this bug.

**Comment by sstagg** [comment]
I realize this is a closed issue, but the last line of the previous post suggests that you might be wanting feedback from other people. I am a user who would love a preference where I could disable drag-and-drop on a text selection! I disable this behavior in every editing program I have from Word to TextWrangler. It drives me crazy as I'm always accidentally missing my selection and when I try to reselect, it ends up moving the text to an unexpected place. Sometimes I don't realize it until it causes a bug somewhere else.
