### ISSUE TITLE
no perl auto_complete

### ISSUE THREAD

**Issue by nokia4321** [Komodo/KomodoEdit#987]
in code intelligence : there is no perl.cix ,so in perl env , eg. chomp defined chop splice and so on function no autocomplete.

**Comment by Naatan** [comment]
I'm not sure I follow, can you please provide more detail? Perhaps a sample snippet and an explanation of what you are expecting to happen?

**Comment by nokia4321** [comment]
Komodo have code hinting function, the key word prompt TAB completion。

**Comment by nokia4321** [comment]
preferences-->codeintelligence-->apicatalogs-->no perl.cix

**Comment by Naatan** [comment]
Those are static catalogs, Komodo does not need them for perl.

**Comment by nokia4321** [comment]
if there is no perl.cix ,No automatic completion perl keywords。

**Comment by nokia4321** [comment]
komodo ide for perl，Auto-complete perl have keywords？how to setting?

**Comment by nokia4321** [comment]
how to set use tab auto-complete keywords?

**Comment by Naatan** [comment]
> if there is no perl.cix ,No automatic completion perl keywords。

This is not how it works, please describe your actual problem. We'll take care of analyzing it and figuring out the underlying issue.

> how to set use tab auto-complete keywords?

Lets keep it to one issue at a time, otherwise this can get really confusing. For general how to questions you should use the forums: http://forum.komodoide.com/c/support

**Comment by nokia4321** [comment]
for perl like this....

![Uploading 2016-01-07_003033.gif…]()

![Uploading 2016-01-07_003033.gif…]()

**Comment by nokia4321** [comment]
ok,thanks.

**Comment by Naatan** [comment]
Those images did not attach properly.

**Comment by mitchell-as** [comment]
Reproduced. Neither Perl nor Python will show completions for built-in functions, but Ruby will.

**Comment by mitchell-as** [comment]
I need to bump this back to at least version 10 because it's a significant change to codeintel for Perl that will likely cause regressions if not done correctly.

Note to self: Ruby and JavaScript explicitly define a trigger for "name" completions, which can autocomplete builtins, local variable names, global class names, etc. Implementing this for Perl will require something similar.

**Comment by cgchoffman** [comment]
> Neither Perl nor Python will show completions for built-in functions

@mitchell-as really?  Python should definitely and I thought Perl did as well.  What examples were you using?

**Comment by mitchell-as** [comment]
@cgchoffman In Perl when I type "cho", I should get completions for "chop", "chomp", "chown", and maybe others, but I do not. In Ruby when I type "put", I get completions for "puts" and "putc". After playing with Python, I see you are correct. However, Python completes after two characters have been typed, not three, so that's why I got thrown off.

**Comment by Naatan** [comment]
So is this still a bug then? Sounds like the current lack of auto completions is "by design" ?

**Comment by mitchell-as** [comment]
I guess you could classify this as "by design", as there's no bug in the code other than the fact it doesn't exist.
